/* DUDUQ WORD SLASH 1.0.14 — Target Shooter shell parity */
(function(){
  "use strict";
  if(!window.DuduQ){console.error("[DuduQ Word Slash] duduq-host.js precisa ser carregado antes.");return;}
  const ID="word-slash",VERSION="1.0.14";
  const RUNTIME="/engine/releases/mechanics/word-slash/1.0.14/DUDUQ_WORD_SLASH.html";
  const SHELL_CSS="/engine/releases/mechanics/word-slash/1.0.14/word-slash-shell.css";
  const isObj=v=>v&&typeof v==="object"&&!Array.isArray(v);
  const text=(v,f="")=>{const s=v==null?"":String(v).trim();return s||f};
  const num=(v,f,min,max)=>{const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f};
  const questionsOf=p=>Array.isArray(p)?p:Array.isArray(p?.questions)?p.questions:Array.isArray(p?.items)?p.items:isObj(p)?[p]:[];
  const normalize=(q,i)=>window.DuduQSchema?.normalizeQuestion?window.DuduQSchema.normalizeQuestion(q,i,{}):q;
  function wsConfig(q){const c=q?.metadata?.wordSlash;if(!isObj(c)||!Array.isArray(c.objects)||c.objects.length<2||!isObj(c.target))throw new Error(`[DuduQ Word Slash] Questão ${q?.id||"sem-id"} inválida.`);return c}
  function defaults(y){y=Math.max(1,Math.min(5,Number(y)||1));return({1:{speedMinMs:3600,speedMaxMs:4600,maxObjects:4,spawnEveryMs:860,timeLimitSeconds:38,correctProbability:.50},2:{speedMinMs:3400,speedMaxMs:4400,maxObjects:4,spawnEveryMs:820,timeLimitSeconds:38,correctProbability:.52},3:{speedMinMs:3200,speedMaxMs:4200,maxObjects:5,spawnEveryMs:760,timeLimitSeconds:40,correctProbability:.54},4:{speedMinMs:3000,speedMaxMs:4000,maxObjects:5,spawnEveryMs:700,timeLimitSeconds:42,correctProbability:.56},5:{speedMinMs:2800,speedMaxMs:3800,maxObjects:6,spawnEveryMs:650,timeLimitSeconds:44,correctProbability:.58}})[y]}
  function build(payload,qs,context){
    const assets=Object.create(null),year=Math.max(1,Math.min(5,Number(context?.year??qs[0]?.year??1)||1));
    const stages=qs.map((q,i)=>{const c=wsConfig(q),d={...defaults(context?.year??q?.year??1),...(isObj(c.difficulty)?c.difficulty:{})},qid=text(q.id,`word-slash-stage-${i+1}`),target={label:text(c.target.label,"TARGET"),value:text(c.target.value),spokenText:text(c.target.spokenText||c.target.value||c.target.label)};if(Array.isArray(c.target.acceptCategories))target.acceptCategories=c.target.acceptCategories.map(x=>text(x)).filter(Boolean);if(c.target.hideValue===true)target.hideValue=true;
      const objects=c.objects.map((raw,j)=>{const o=isObj(raw)?raw:{},oid=text(o.id,`${qid}-object-${j+1}`),src=text(o.imageSrc||o.image?.src);let key=text(o.imageAssetKey);if(src){key=key||`ws-${qid}-${oid}`;assets[key]=src}const out={id:oid,type:text(o.type,key?"image":o.colorHex?"color":"word"),label:text(o.label),value:text(o.value,o.label||o.alt||oid),category:text(o.category),weight:num(o.weight,1,1,20)};if(key){out.imageAssetKey=key;out.alt=text(o.alt,o.label||o.value||oid)}if(o.colorHex)out.colorHex=text(o.colorHex);return out});
      return{id:qid,title:text(q?.metadata?.screenTitle||q?.metadata?.title||q?.statement,"Word Slash"),instruction:text(q?.instruction,"CORTE SOMENTE OS ELEMENTOS CORRETOS.").toLocaleUpperCase("pt-BR"),audioText:text(c.audioText||q?.audio?.text||q?.media?.audio?.text||q?.instruction),mode:text(c.mode,"correct-word"),target,goal:Math.round(num(c.goal,3,1,20)),difficulty:{speedMinMs:Math.round(num(d.speedMinMs,3600,1200,12000)),speedMaxMs:Math.round(num(d.speedMaxMs,4600,1400,14000)),maxObjects:Math.round(num(d.maxObjects,4,2,10)),spawnEveryMs:Math.round(num(d.spawnEveryMs,860,300,3000)),timeLimitSeconds:Math.round(num(d.timeLimitSeconds,38,15,120)),correctProbability:num(d.correctProbability,.5,.14,.85)},objects};
    });
    return{year,config:{schemaVersion:1,mechanic:ID,version:"1.0.0",title:text(payload?.title||qs[0]?.metadata?.screenTitle,"Word Slash"),settings:{interfaceLocale:"pt-BR",speechLocale:"en-US",targetGrade:year,extraTimeSeconds:12,wrongPenalty:0},stages},assets};
  }
  const safeJson=v=>JSON.stringify(v,null,2).replace(/</g,"\\u003c").replace(/`/g,"\\`").replace(/\$\{/g,"\\${");
  function required(html,from,to,label){if(!html.includes(from))throw new Error(`[DuduQ Word Slash 1.0.14] Marcador ausente: ${label}.`);return html.replace(from,to)}
  function injectConfig(html,config){const h='var WORD_SLASH_ACTIVITY_JSON = String.raw`',t='`;\n\n  var WORD_SLASH_CONFIG = JSON.parse(WORD_SLASH_ACTIVITY_JSON);',a=html.indexOf(h),s=a+h.length,e=html.indexOf(t,s);if(a<0||e<0)throw new Error("JSON marker ausente");return html.slice(0,s)+safeJson(config)+html.slice(e)}
  function injectAssets(html,assets){return required(html,'var WORD_SLASH_ASSETS = {\n    ...DRAG_DROP_UNIVERSAL_ASSETS\n  };',`var WORD_SLASH_ASSETS = {\n    ...DRAG_DROP_UNIVERSAL_ASSETS,\n    ...${safeJson(assets)}\n  };`,"assets")}
  function completion(html){return required(html,"autoPlayInstruction: true,\n        gamificationPolicy:",'autoPlayInstruction: true,\n        hostedByDuduQ: true,\n        onLessonComplete: () => window.parent.postMessage({type:"DUDUQ_WORD_SLASH_COMPLETE"}, "*"),\n        gamificationPolicy:',"completion bridge")}
  function stampYear(html,year){return html.replace(/<html([^>]*)>/i,(_,a)=>`<html${a} data-duduq-ano="${year}" data-duduq-ano-ativo="${year}">`)}
  function rootFix(html){
    html=required(html,'    const replayTarget = useCallback(() => {\n      const spokenText = question.target.spokenText || question.target.value || question.audioText || question.instruction;\n      audio.playText(`word-slash:${question.id}:target`, spokenText, "en-US");\n    }, [audio, question]);','    const replayTarget = useCallback(() => {\n      audio.playInstruction(true);\n    }, [audio]);',"playInstruction");
    html=required(html,'"data-playing": audio.activeAudioKey === `word-slash:${question.id}:target` ? "true" : "false",','"data-playing": audio.isPlaying ? "true" : "false",',"isPlaying");
    html=required(html,'"aria-label": "Ouvir novamente o alvo em inglês"','"aria-label": audio.isPlaying ? "Áudio em reprodução" : "Ouvir instrução"',"aria áudio");
    html=required(html,'              "🔊"\n            )',`              h("svg", {viewBox:"0 0 24 24",width:23,height:23,"aria-hidden":"true",focusable:"false",style:{display:"block",color:"currentColor"}},h("path",{d:"M11 5 6.5 9H3v6h3.5L11 19V5Z",fill:"currentColor"}),h("path",{d:"M15 8.5c1.3 1.8 1.3 5.2 0 7",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round"}),h("path",{d:"M18 6c2.7 3.4 2.7 8.6 0 12",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round"}))\n            )`,"SVG áudio");
    return html;
  }
  function shellLink(html){const link=`<link id="duduq-word-slash-1-0-13-shell" rel="stylesheet" href="${SHELL_CSS}">`;return html.includes("</head>")?html.replace("</head>",link+"\n</head>"):html}
  function syncChrome(doc,context,title){if(!doc?.documentElement)return;if(context?.year!=null){doc.documentElement.setAttribute("data-duduq-ano-ativo",String(context.year));doc.documentElement.setAttribute("data-duduq-ano",String(context.year))}const h=doc.querySelector(".duduq-engine-heading h1");if(h&&h.textContent!==title)h.textContent=title;const i=Number.isFinite(context?.stepIndex)?context.stepIndex:0,total=Number.isFinite(context?.totalSteps)?Math.max(1,context.totalSteps):1,s=doc.querySelector(".duduq-progress-copy strong");if(s)s.textContent=`Etapa ${Math.min(i+1,total)} de ${total}`}
  function validate(payload){try{const qs=questionsOf(payload);if(!qs.length)return false;qs.map(normalize).forEach(wsConfig);return true}catch(e){console.error(e);return false}}
  function mount({container,payload,context={},onComplete}){const qs=questionsOf(payload).map(normalize);if(!container||!qs.length)throw new Error("[DuduQ Word Slash] Payload/container inválido.");qs.forEach(wsConfig);container.innerHTML="";const wrap=document.createElement("div");wrap.className="duduq-mechanic-frame";Object.assign(wrap.style,{width:"100%",height:"100%",minHeight:"0",overflow:"hidden",position:"relative"});const frame=document.createElement("iframe");frame.title="DuduQ — Word Slash";frame.setAttribute("allow","autoplay; fullscreen");frame.setAttribute("allowfullscreen","");Object.assign(frame.style,{width:"100%",height:"100%",minHeight:"0",border:"0",display:"block",background:"transparent"});wrap.appendChild(frame);container.appendChild(wrap);let dead=false,done=false,observer=null;const title=text(payload?.title||qs[0]?.metadata?.screenTitle,"Word Slash"),msg=e=>{if(e.source===frame.contentWindow&&e.data?.type==="DUDUQ_WORD_SLASH_COMPLETE"&&!done){done=true;onComplete?.({type:"complete",completed:true,mechanic:ID})}};window.addEventListener("message",msg);frame.addEventListener("load",()=>{try{syncChrome(frame.contentDocument,context,title);observer=new MutationObserver(()=>syncChrome(frame.contentDocument,context,title));observer.observe(frame.contentDocument.body,{childList:true,subtree:true,characterData:true})}catch(_){}});
    const base=(window.DUDUQ_ENGINE_BASE?String(window.DUDUQ_ENGINE_BASE).replace(/\/$/,""):".")+RUNTIME+`?engineAdapter=${VERSION}`;
    fetch(base).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}).then(html=>{if(dead)return;const b=build(payload,qs,context);let out=injectConfig(html,b.config);out=injectAssets(out,b.assets);out=completion(out);out=rootFix(out);out=shellLink(out);out=stampYear(out,b.year);frame.srcdoc=out}).catch(e=>{console.error("[DuduQ Word Slash 1.0.14]",e);if(!dead)container.textContent="Erro ao preparar a atividade Word Slash."});
    return()=>{dead=true;observer?.disconnect();window.removeEventListener("message",msg);try{frame.src="about:blank"}catch(_){}wrap.remove()};
  }
  window.DuduQ.registerMechanic({id:ID,version:VERSION,validate,mount,metadata:{name:"Word Slash",category:"reconhecimento-rapido",active:true,acceptsSchema:"1.0.0",globalProgress:true,literacyFriendly:true,supportsMedia:["text","image","color","audio-instruction"],gradeRange:{minimum:1,maximum:5},routerProfile:{name:"Word Slash",active:true,baseScore:84,answerTypes:["single","multiple"],answerTypeWeights:{single:34,multiple:32},minAlternatives:2,maxAlternatives:10,supports:{questionImage:false,optionImageUrl:true,optionImageAssetKey:true,questionAudio:true,optionAudio:false},metadata:{category:"reconhecimento-rapido",earlyLiteracy:true,speedBased:true,supportsCategories:true,runtimeRootFix:"target-shell-card-typography-parity-1.0.14"},tags:["word","image","category","listening","speed"]}}});
})();
