/* DUDUQ English Year 3 — Module 05 — source-approved thin content */
(function(){"use strict";const F=window.DuduQYear3Factory;if(!F)throw new Error("DuduQYear3Factory não carregado.");F.publish({module:5,version:"1.0.0-scale-bootstrap",title:"Shapes, Colors, Numbers & Size",objective:"Descrever formas por quantidade, cor e tamanho em situações visuais, privilegiando significado.",items:[
{id:"EN3-M5-01",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar formas geométricas em inglês.",prompt:"Observe a forma e escolha seu nome em inglês.",alternatives:[{id:"A",text:"rectangle"},{id:"B",text:"circle"},{id:"C",text:"triangle"},{id:"D",text:"square"}],answer:{id:"B",text:"circle"},media:"Imagem obrigatória: circle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"circle",listenText:"",mechanic:"drag-drop",topic:"SHAPES"},
{id:"EN3-M5-02",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar formas geométricas em inglês.",prompt:"Qual palavra em inglês nomeia a forma mostrada?",alternatives:[{id:"A",text:"circle"},{id:"B",text:"triangle"},{id:"C",text:"rectangle"},{id:"D",text:"square"}],answer:{id:"C",text:"rectangle"},media:"Imagem obrigatória: rectangle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"rectangle",listenText:"",mechanic:"drag-drop",topic:"SHAPES"},
{id:"EN3-M5-03",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar formas geométricas em inglês.",prompt:"Toque no cartão correspondente à forma da imagem.",alternatives:[{id:"A",text:"circle"},{id:"B",text:"rectangle"},{id:"C",text:"square"},{id:"D",text:"triangle"}],answer:{id:"D",text:"triangle"},media:"Imagem obrigatória: triangle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"triangle",listenText:"",mechanic:"drag-drop",topic:"SHAPES"},
{id:"EN3-M5-04",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar formas geométricas em inglês.",prompt:"A imagem mostra uma forma. Escolha o nome em inglês.",alternatives:[{id:"A",text:"square"},{id:"B",text:"circle"},{id:"C",text:"rectangle"},{id:"D",text:"triangle"}],answer:{id:"A",text:"square"},media:"Imagem obrigatória: square. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"square",listenText:"",mechanic:"drag-drop",topic:"SHAPES"},
{id:"EN3-M5-05",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar formas geométricas em inglês.",prompt:"Encontre o nome correto da forma geométrica.",alternatives:[{id:"A",text:"circle"},{id:"B",text:"star"},{id:"C",text:"rectangle"},{id:"D",text:"triangle"}],answer:{id:"B",text:"star"},media:"Imagem obrigatória: star. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"star",listenText:"",mechanic:"drag-drop",topic:"SHAPES"},
{id:"EN3-M5-06",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e forma.",prompt:"Observe um círculo vermelho. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"one red circle"},{id:"B",text:"one blue circle"},{id:"C",text:"two red circles"},{id:"D",text:"one red square"}],answer:{id:"A",text:"one red circle"},media:"Imagem obrigatória: one red circle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"one red circle",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"},
{id:"EN3-M5-07",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e forma.",prompt:"Observe 6 retângulos azuis. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"six blue rectangles"},{id:"B",text:"five blue rectangles"},{id:"C",text:"six red rectangles"},{id:"D",text:"six blue circles"}],answer:{id:"A",text:"six blue rectangles"},media:"Imagem obrigatória: 6 blue rectangles. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"6 blue rectangles",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"},
{id:"EN3-M5-08",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Combinar quantidade, tamanho e forma.",prompt:"Observe um círculo grande. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"one big circle"},{id:"B",text:"one small circle"},{id:"C",text:"one big square"},{id:"D",text:"two big circles"}],answer:{id:"A",text:"one big circle"},media:"Imagem obrigatória: one big circle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"one big circle",listenText:"",mechanic:"drag-drop",topic:"SHAPES & SIZE"},
{id:"EN3-M5-09",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Combinar quantidade, tamanho e forma.",prompt:"Observe 3 círculos pequenos. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"three small circles"},{id:"B",text:"three big circles"},{id:"C",text:"two small circles"},{id:"D",text:"three small squares"}],answer:{id:"A",text:"three small circles"},media:"Imagem obrigatória: 3 small circles. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"3 small circles",listenText:"",mechanic:"drag-drop",topic:"SHAPES & SIZE"},
{id:"EN3-M5-10",status:"Reescrever",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, tamanho e forma em uma expressão curta.",prompt:"Observe 2 triângulos grandes. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"two big triangles"},{id:"B",text:"two small triangles"},{id:"C",text:"three big triangles"},{id:"D",text:"two big squares"}],answer:{id:"A",text:"two big triangles"},media:"Imagem obrigatória: 2 big triangles. Formato sugerido: Imagem → expressão.",format:"Imagem → expressão.",visualQuery:"2 big triangles",listenText:"",mechanic:"drag-drop",topic:"SHAPES & SIZE"},
{id:"EN3-M5-11",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e forma.",prompt:"Observe 2 estrelas amarelas. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"two yellow stars"},{id:"B",text:"two yellow circles"},{id:"C",text:"three yellow stars"},{id:"D",text:"two blue stars"}],answer:{id:"A",text:"two yellow stars"},media:"Imagem obrigatória: 2 yellow stars. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"2 yellow stars",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"},
{id:"EN3-M5-12",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e forma.",prompt:"Observe 4 quadrados verdes. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"four green squares"},{id:"B",text:"four blue squares"},{id:"C",text:"three green squares"},{id:"D",text:"four green rectangles"}],answer:{id:"A",text:"four green squares"},media:"Imagem obrigatória: 4 green squares. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"4 green squares",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"},
{id:"EN3-M5-13",status:"Reescrever",difficulty:"Difícil",skill:"Leitura / compreensão",ability:"Reconhecer uma descrição natural de quantidade + tamanho + forma.",prompt:"Observe 5 estrelas pequenas. Qual descrição é a mais precisa?",alternatives:[{id:"A",text:"five small stars"},{id:"B",text:"five big stars"},{id:"C",text:"four small stars"},{id:"D",text:"five small circles"}],answer:{id:"A",text:"five small stars"},media:"Imagem obrigatória: 5 small stars. Formato sugerido: Imagem → expressão.",format:"Imagem → expressão.",visualQuery:"5 small stars",listenText:"",mechanic:"drag-drop",topic:"SHAPES & SIZE"},
{id:"EN3-M5-14",status:"Reescrever",difficulty:"Difícil",skill:"Compreensão multimodal",ability:"Compreender uma descrição com quantidade + cor + forma.",prompt:"Observe 7 quadrados vermelhos. Qual alternativa descreve a imagem?",alternatives:[{id:"A",text:"seven blue squares"},{id:"B",text:"six red squares"},{id:"C",text:"seven red squares"},{id:"D",text:"seven red rectangles"}],answer:{id:"C",text:"seven red squares"},media:"Imagem obrigatória: 7 red squares. Formato sugerido: Imagem → expressão.",format:"Imagem → expressão.",visualQuery:"7 red squares",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"},
{id:"EN3-M5-15",status:"Reescrever",difficulty:"Difícil",skill:"Leitura + produção guiada",ability:"Selecionar a forma plural adequada em contexto visual.",prompt:"Observe vários retângulos. Qual palavra completa a legenda: “blue ___”?",alternatives:[{id:"A",text:"rectangle"},{id:"B",text:"rectangles"},{id:"C",text:"triangle"},{id:"D",text:"square"}],answer:{id:"B",text:"rectangles"},media:"Imagem obrigatória: vários blue rectangles. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"6 blue rectangles",listenText:"",mechanic:"drag-drop",topic:"SHAPES, COLORS & NUMBERS"}
]});})();
