import { chromium } from "playwright";
const BASE=process.env.BASE_URL||"http://127.0.0.1:4173";
const assert=(c,m)=>{if(!c)throw new Error(m)};
const report={items:[],clusters:{},P0:[],P1:[],P2:[],runtime:{pageErrors:[],critical404:[]},functional:[]};
const add=(sev,q,detail)=>report[sev].push({year:q.year,module:q.module,id:q.id,detail});

function walkModule(root,year,module){
  const seen=new Set();function walk(v){if(!v||typeof v!=="object"||seen.has(v))return null;seen.add(v);if(Array.isArray(v.activities)&&Number(v.year)===year&&Number(v.module)===module)return v;for(const x of Object.values(v)){const f=walk(x);if(f)return f}return null}return walk(root);
}
function isTS(a,q){return String(a?.mechanic||q?.delivery?.mechanic||q?.renderer||"").toLowerCase().replace(/_/g,"-")==="target-shooter"}
function cluster(q){const c=q?.metadata?.targetShooter||{},items=c.items||[],mode=String(c.mode||"").toLowerCase();const audio=Boolean(c.audioText||q?.audio?.text||q?.audio?.src||q?.media?.audio?.text);const image=items.some(x=>x?.image||x?.imageUrl||x?.imageAsset||x?.imageAssetKey)||q?.image?.src||q?.media?.image?.src;const numeric=items.some(x=>/^\d+$/.test(String(x?.label||"")));return [mode||"default",audio?"audio":"no-audio",image?"image":"text",numeric?"numeric":"non-numeric"].join("|")}
async function ttsStub(page){await page.addInitScript(()=>{const synth={speaking:false,pending:false,paused:false,getVoices:()=>[],cancel(){this.speaking=false},pause(){},resume(){},speak(u){this.speaking=true;try{u?.onstart?.({type:"start"})}catch{};queueMicrotask(()=>{this.speaking=false;try{u?.onend?.({type:"end"})}catch{}})}};try{Object.defineProperty(globalThis,"speechSynthesis",{value:synth,configurable:true})}catch{globalThis.speechSynthesis=synth}})}
async function mount(page,q){return page.evaluate(q=>{document.getElementById("ts-baseline-host")?.remove();const host=document.createElement("div");host.id="ts-baseline-host";host.style.cssText="position:fixed;inset:0;z-index:999999;background:#fff";document.body.appendChild(host);window.__TS_BASELINE_DONE__=[];const mech=window.DuduQ?.getMechanic?.("target-shooter");if(!mech)throw new Error("Target Shooter não registrado");if(mech.version!=="1.0.21")throw new Error(`Target Shooter ${mech.version}`);if(!mech.validate(q))throw new Error(`validate=false ${q.id}`);window.__TS_BASELINE_DESTROY__=mech.mount({container:host,payload:q,context:{subject:"english",year:q.year,module:q.module,stepId:q.id,stepIndex:0,totalSteps:1},onComplete:r=>window.__TS_BASELINE_DONE__.push(r)});return true},q)}
async function frameReady(page){await page.locator("#ts-baseline-host iframe").waitFor({state:"attached",timeout:8000});const h=await page.locator("#ts-baseline-host iframe").elementHandle();const f=await h.contentFrame();await f.waitForLoadState("domcontentloaded").catch(()=>{});await f.locator("body").waitFor({state:"visible",timeout:8000});await f.waitForTimeout(180);return f}
async function inspect(frame,q,viewport){const c=q.metadata.targetShooter,items=c.items||[];return frame.evaluate(({items,viewport})=>{const all=[...document.querySelectorAll("*")];const targets=all.filter(el=>{const cls=String(el.className||"");return /duduq-ts-(?:target|option|choice)/i.test(cls)||[...el.attributes||[]].some(a=>/^(data-(?:target|item|option|answer)(?:-id)?)$/i.test(a.name))});const imgs=[...document.images].filter(x=>x.offsetWidth||x.offsetHeight||x.getClientRects().length).map(x=>({src:x.currentSrc||x.src||"",alt:x.alt||"",w:x.naturalWidth,h:x.naturalHeight,rect:x.getBoundingClientRect().toJSON?.()||{width:x.getBoundingClientRect().width,height:x.getBoundingClientRect().height}}));const buttons=[...document.querySelectorAll("button,[role=button]")].filter(x=>x.offsetWidth||x.offsetHeight||x.getClientRects().length).map(x=>{const r=x.getBoundingClientRect();return {text:(x.textContent||"").trim().slice(0,80),w:r.width,h:r.height,cls:String(x.className||"")}});const body=document.body.getBoundingClientRect();return {targets:targets.length,imgs,buttons,scrollW:document.documentElement.scrollWidth,clientW:document.documentElement.clientWidth,scrollH:document.documentElement.scrollHeight,clientH:document.documentElement.clientHeight,body:{w:body.width,h:body.height},itemCount:items.length,viewport}}, {items,viewport})}
async function findTarget(frame,item){const id=String(item.id),label=String(item.label||"").trim();const selectors=[`[data-target-id="${CSS.escape(id)}"]`,`[data-item-id="${CSS.escape(id)}"]`,`[data-option-id="${CSS.escape(id)}"]`,`[data-answer-id="${CSS.escape(id)}"]`,`[data-id="${CSS.escape(id)}"]`,`[data-value="${CSS.escape(id)}"]`];for(const s of selectors){const loc=frame.locator(s).filter({visible:true}).first();if(await loc.count().catch(()=>0))return loc}if(label){const exact=frame.getByText(label,{exact:true}).first();if(await exact.count().catch(()=>0)){const button=exact.locator("xpath=ancestor-or-self::button[1]");if(await button.count().catch(()=>0))return button;return exact}const img=frame.locator(`img[alt="${label.replace(/"/g,'\\"')}"]`).first();if(await img.count().catch(()=>0)){const button=img.locator("xpath=ancestor-or-self::button[1]");if(await button.count().catch(()=>0))return button;return img}}return null}
async function behavior(page,q,key){await mount(page,q);const f=await frameReady(page),c=q.metadata.targetShooter,items=c.items||[],correct=new Set((c.correctIds||[]).map(String)),wrong=items.find(x=>!correct.has(String(x.id))),good=items.find(x=>correct.has(String(x.id)));if(!wrong||!good)return {cluster:key,status:"N/A_NO_SAFE_WRONG",id:q.id};const bad=await findTarget(f,wrong),ok=await findTarget(f,good);if(!bad||!ok)return {cluster:key,status:"TEST_GAP_TARGET_LOCATOR",id:q.id};await bad.click({force:true});await page.waitForTimeout(450);const afterWrong=await page.evaluate(()=>window.__TS_BASELINE_DONE__.length);if(afterWrong!==0)return {cluster:key,status:"P0_WRONG_COMPLETED",id:q.id};const ok2=await findTarget(f,good);if(!ok2)return {cluster:key,status:"TEST_GAP_CORRECT_LOCATOR_AFTER_RETRY",id:q.id};await ok2.click({force:true});await page.waitForFunction(()=>window.__TS_BASELINE_DONE__.length>0,null,{timeout:7000});return {cluster:key,status:"PASS",id:q.id,wrongRetry:true,success:true}}

const browser=await chromium.launch({headless:true});
try{
  const all=[];
  for(let year=1;year<=5;year++)for(let module=1;module<=6;module++){
    const page=await browser.newPage({viewport:{width:1366,height:768}});await ttsStub(page);page.on("pageerror",e=>report.runtime.pageErrors.push({year,module,error:String(e?.message||e)}));page.on("response",r=>{if(r.status()===404){const u=r.url();if(u.includes("/engine/")||u.includes(`/content/english/year-${year}/`))report.runtime.critical404.push({year,module,url:u})}});
    try{const mm=String(module).padStart(2,"0"),res=await page.goto(`${BASE}/content/english/year-${year}/module-${mm}/?qa=ts-baseline-1021`,{waitUntil:"domcontentloaded",timeout:35000});assert(res?.ok(),`Y${year} M${mm} HTTP ${res?.status()}`);await page.waitForFunction(()=>window.DUDUQ_ENGINE_READY===true,null,{timeout:35000});const data=await page.evaluate(({year,module})=>{const seen=new Set();function walk(v){if(!v||typeof v!=="object"||seen.has(v))return null;seen.add(v);if(Array.isArray(v.activities)&&Number(v.year)===year&&Number(v.module)===module)return v;for(const x of Object.values(v)){const f=walk(x);if(f)return f}return null}const m=walk(window.DUDUQ_CONTENT||{});if(!m)return null;const out=[];for(const a of m.activities||[])for(const q of a.questions||[])if(String(a?.mechanic||q?.delivery?.mechanic||q?.renderer||"").toLowerCase().replace(/_/g,"-")==="target-shooter")out.push(q);return out},{year,module});for(const q of data||[])all.push({...q,year,module})}finally{await page.close()}
  }
  assert(all.length===66,`inventário TS ${all.length}/66`);
  const reps=new Map();
  for(const q of all){const key=cluster(q),c=q.metadata?.targetShooter||{},items=c.items||[],ids=new Set(items.map(x=>String(x.id))),correct=(c.correctIds||[]).map(String);report.clusters[key]=(report.clusters[key]||0)+1;if(!reps.has(key))reps.set(key,q);let status="PASS";if(items.length<2||!correct.length||correct.some(x=>!ids.has(x))){add("P0",q,"contrato items/correctIds inválido");status="P0"}const size=Number(c.difficulty?.targetSize||150);if(size<44){add("P0",q,`targetSize=${size}`);status="P0"}if(Number(c.difficulty?.timeLimitMs||0)>0||String(c.difficulty?.timerMode||"none").toLowerCase()!=="none"){add("P0",q,"timer ativo");status="P0"}report.items.push({year:q.year,module:q.module,id:q.id,cluster:key,status})}
  // Renderiza todos os 66 em desktop para verificar abertura, alvos, imagens e overflow.
  for(const q of all){const page=await browser.newPage({viewport:{width:1366,height:768}});await ttsStub(page);try{const mm=String(q.module).padStart(2,"0");await page.goto(`${BASE}/content/english/year-${q.year}/module-${mm}/?qa=ts-render-${q.id}`,{waitUntil:"domcontentloaded",timeout:35000});await page.waitForFunction(()=>window.DUDUQ_ENGINE_READY===true,null,{timeout:35000});await mount(page,q);const f=await frameReady(page),v=await inspect(f,q,"1366x768");if(v.itemCount>=2&&v.targets===0)add("P0",q,"nenhum alvo renderizado");if(v.imgs.some(x=>!x.w||!x.h))add("P0",q,"imagem renderizada quebrada");if(v.scrollW>v.clientW+2)add("P1",q,`overflow horizontal ${v.scrollW}/${v.clientW}`);const minControl=v.buttons.filter(b=>/target|option|choice/i.test(b.cls));if(minControl.some(b=>b.w<44||b.h<44))add("P1",q,"alvo clicável menor que 44px");}catch(e){add("P0",q,`render: ${String(e?.message||e)}`)}finally{await page.close()}}
  // Funcional por cluster real, sem explosão de runners.
  for(const [key,q] of reps){const page=await browser.newPage({viewport:{width:1366,height:768}});await ttsStub(page);try{const mm=String(q.module).padStart(2,"0");await page.goto(`${BASE}/content/english/year-${q.year}/module-${mm}/?qa=ts-behavior-${encodeURIComponent(key)}`,{waitUntil:"domcontentloaded",timeout:35000});await page.waitForFunction(()=>window.DUDUQ_ENGINE_READY===true,null,{timeout:35000});const r=await behavior(page,q,key);report.functional.push(r);if(r.status.startsWith("P0"))add("P0",q,r.status);else if(r.status.startsWith("TEST_GAP"))report.P2.push({year:q.year,module:q.module,id:q.id,detail:r.status})}catch(e){report.P2.push({year:q.year,module:q.module,id:q.id,detail:`functional TEST_GAP: ${String(e?.message||e)}`})}finally{await page.close()}}
  // Responsividade visual representativa por cluster em quatro viewports + zoom 200% equivalente.
  const viewports=[[1366,768],[768,1024],[390,844],[360,640],[683,384]];
  for(const [key,q] of reps){for(const [w,h] of viewports){const page=await browser.newPage({viewport:{width:w,height:h}});await ttsStub(page);try{const mm=String(q.module).padStart(2,"0");await page.goto(`${BASE}/content/english/year-${q.year}/module-${mm}/?qa=ts-vp`,{waitUntil:"domcontentloaded",timeout:35000});await page.waitForFunction(()=>window.DUDUQ_ENGINE_READY===true,null,{timeout:35000});await mount(page,q);const f=await frameReady(page),v=await inspect(f,q,`${w}x${h}`);if(v.scrollW>v.clientW+2)add("P1",q,`${key} overflow ${w}x${h}: ${v.scrollW}/${v.clientW}`)}catch(e){report.P2.push({year:q.year,module:q.module,id:q.id,detail:`viewport ${w}x${h} TEST_GAP: ${String(e?.message||e)}`})}finally{await page.close()}}}
}finally{await browser.close()}
const unique=(xs)=>[...new Map(xs.map(x=>[`${x.year}/${x.module}/${x.id}/${x.detail}`,x])).values()];report.P0=unique(report.P0);report.P1=unique(report.P1);report.P2=unique(report.P2);console.log(JSON.stringify({status:report.P0.length?"BASELINE_FINDINGS":"BASELINE_PASS",audited:report.items.length,total:66,clusters:report.clusters,P0:report.P0,P1:report.P1,P2:report.P2,functional:report.functional,runtime:report.runtime},null,2));if(report.runtime.critical404.length||report.runtime.pageErrors.length)process.exitCode=2;