import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const expect=(c,m)=>{if(!c)throw new Error(m)};
const hash=p=>execFileSync("git",["hash-object",p],{cwd:root,encoding:"utf8"}).trim();
const candidatePath="engine/releases/mechanics/drag-drop/2.0.25/drag-drop.js";
const candidate=read(candidatePath);
expect(hash("engine/releases/mechanics/drag-drop/2.0.24/drag-drop.js")==="2cfa8729ee04f0da2866048c443abf6dcc27b32c","2.0.24 foi alterada.");
expect(candidate.includes('const VERSION = "2.0.25"'),"identidade 2.0.25 ausente");
expect(candidate.includes('BASE_URL = "/engine/releases/mechanics/drag-drop/2.0.24/drag-drop.js"'),"base 2.0.24 ausente");
expect(candidate.includes("data-dd225-smart-snap"),"sentinela smart snap ausente");
expect(candidate.includes('data-dd225-instant-validation'),"sentinela instant validation ausente");
expect(candidate.includes("positionedAnyCount === 1"),"single-choice não habilita confirmar de forma neutra");
expect(candidate.includes('question.mode === "single-choice"')&&candidate.includes("var chosen = question.items.find"),"scoring single-choice no submit ausente");
expect(candidate.includes("resolveSmartTarget"),"resolver smart snap ausente");
expect(candidate.includes("magneticRadiusPx:104")&&candidate.includes("snapRadiusPx:44"),"tolerâncias smart snap ausentes");
expect(candidate.includes("setRetryAnimating(true)")&&candidate.includes("wrongItemIds.slice()"),"retry parcial compartilhado ausente");
expect(candidate.includes("onRootKeyDown")&&candidate.includes('event.key !== "Escape"'),"Escape acessível ausente");
expect(candidate.includes("object-fit: contain"),"proteção de mídia ausente");
expect(candidate.includes("'rejectWrongDrop: false'"),"posicionamento neutro pré-CONFIRMAR não foi aplicado");
expect(!candidate.includes("React CDN"),"runtime não deve importar React CDN");
console.log("PASS — Drag & Drop 2.0.25 Smart Confirm static contract");
