/* DUDUQ English Year 3 — Module 06 — source-approved thin content */
(function(){"use strict";const F=window.DuduQYear3Factory;if(!F)throw new Error("DuduQYear3Factory não carregado.");F.publish({module:6,version:"1.0.0-scale-bootstrap",title:"Transportation & Body Description",objective:"Reconhecer meios de transporte e partes do corpo e produzir descrições curtas com cor, quantidade e tamanho.",items:[
{id:"EN3-M6-01",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar meios de transporte em inglês.",prompt:"Observe o meio de transporte e escolha seu nome em inglês.",alternatives:[{id:"A",text:"bus"},{id:"B",text:"car"},{id:"C",text:"truck"},{id:"D",text:"plane"}],answer:{id:"B",text:"car"},media:"Imagem obrigatória: car. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"car",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION"},
{id:"EN3-M6-02",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar meios de transporte em inglês.",prompt:"Qual palavra em inglês nomeia o transporte da imagem?",alternatives:[{id:"A",text:"car"},{id:"B",text:"truck"},{id:"C",text:"bus"},{id:"D",text:"plane"}],answer:{id:"C",text:"bus"},media:"Imagem obrigatória: bus. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"bus",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION"},
{id:"EN3-M6-03",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar meios de transporte em inglês.",prompt:"Toque no cartão que corresponde ao veículo mostrado.",alternatives:[{id:"A",text:"car"},{id:"B",text:"bus"},{id:"C",text:"plane"},{id:"D",text:"truck"}],answer:{id:"D",text:"truck"},media:"Imagem obrigatória: truck. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"truck",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION"},
{id:"EN3-M6-04",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar meios de transporte em inglês.",prompt:"A imagem mostra um meio de transporte. Escolha o nome correto.",alternatives:[{id:"A",text:"plane"},{id:"B",text:"car"},{id:"C",text:"bus"},{id:"D",text:"truck"}],answer:{id:"A",text:"plane"},media:"Imagem obrigatória: plane. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"plane",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION"},
{id:"EN3-M6-05",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar meios de transporte em inglês.",prompt:"Encontre o termo em inglês que identifica o transporte.",alternatives:[{id:"A",text:"car"},{id:"B",text:"train"},{id:"C",text:"bus"},{id:"D",text:"truck"}],answer:{id:"B",text:"train"},media:"Imagem obrigatória: train. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"train",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION"},
{id:"EN3-M6-06",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Compreender uma descrição de transporte com cor.",prompt:"Observe o carro verde. Qual frase descreve a imagem?",alternatives:[{id:"A",text:"This is a green car."},{id:"B",text:"This is a blue car."},{id:"C",text:"This is a green bus."},{id:"D",text:"This is a big green car."}],answer:{id:"A",text:"This is a green car."},media:"Imagem obrigatória: green car, sem pista de tamanho. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"green car",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION & COLORS"},
{id:"EN3-M6-07",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Compreender uma descrição de transporte com duas cores.",prompt:"Observe o ônibus vermelho e azul. Qual frase descreve a imagem?",alternatives:[{id:"A",text:"This is a red and blue bus."},{id:"B",text:"This is a red bus."},{id:"C",text:"This is a blue train."},{id:"D",text:"This is a red and blue car."}],answer:{id:"A",text:"This is a red and blue bus."},media:"Imagem obrigatória: red and blue bus. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"red and blue bus",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION & COLORS"},
{id:"EN3-M6-08",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Compreender uma descrição de transporte com tamanho.",prompt:"Observe o caminhão grande. Qual frase descreve a imagem?",alternatives:[{id:"A",text:"This is a big truck."},{id:"B",text:"This is a small truck."},{id:"C",text:"This is a big bus."},{id:"D",text:"This is a big car."}],answer:{id:"A",text:"This is a big truck."},media:"Imagem obrigatória: big truck. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"big truck",listenText:"",mechanic:"drag-drop",topic:"TRANSPORTATION & SIZE"},
{id:"EN3-M6-09",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar partes do corpo e descrevê-las.",prompt:"Observe a parte do corpo destacada e escolha seu nome em inglês.",alternatives:[{id:"A",text:"nose"},{id:"B",text:"hands"},{id:"C",text:"eyes"},{id:"D",text:"hair"}],answer:{id:"B",text:"hands"},media:"Imagem obrigatória: hands. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"hands",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS"},
{id:"EN3-M6-10",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar partes do corpo e descrevê-las.",prompt:"Qual palavra em inglês corresponde à parte indicada?",alternatives:[{id:"A",text:"hands"},{id:"B",text:"eyes"},{id:"C",text:"nose"},{id:"D",text:"hair"}],answer:{id:"C",text:"nose"},media:"Imagem obrigatória: nose. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"nose",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS"},
{id:"EN3-M6-11",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar partes do corpo e descrevê-las.",prompt:"Toque no cartão que nomeia a parte do corpo da imagem.",alternatives:[{id:"A",text:"hands"},{id:"B",text:"nose"},{id:"C",text:"hair"},{id:"D",text:"eyes"}],answer:{id:"D",text:"eyes"},media:"Imagem obrigatória: eyes. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"eyes",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS"},
{id:"EN3-M6-12",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Identificar partes do corpo e descrevê-las.",prompt:"A imagem destaca uma parte do corpo. Escolha a opção correta.",alternatives:[{id:"A",text:"hair"},{id:"B",text:"hands"},{id:"C",text:"nose"},{id:"D",text:"eyes"}],answer:{id:"A",text:"hair"},media:"Imagem obrigatória: hair. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"hair",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS"},
{id:"EN3-M6-13",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, tamanho e parte do corpo.",prompt:"Observe duas mãos grandes. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"two big hands"},{id:"B",text:"two small hands"},{id:"C",text:"one big hand"},{id:"D",text:"two big feet"}],answer:{id:"A",text:"two big hands"},media:"Imagem obrigatória: two big hands. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"two big hands",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS & SIZE"},
{id:"EN3-M6-14",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e parte do corpo.",prompt:"Observe dois olhos verdes. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"two green eyes"},{id:"B",text:"two blue eyes"},{id:"C",text:"one green eye"},{id:"D",text:"two green hands"}],answer:{id:"A",text:"two green eyes"},media:"Imagem obrigatória: two green eyes. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"two green eyes",listenText:"",mechanic:"drag-drop",topic:"BODY PARTS & COLORS"},
{id:"EN3-M6-15",status:"Reescrever",difficulty:"Difícil",skill:"Compreensão multimodal",ability:"Relacionar uma característica visual simples à expressão brown hair.",prompt:"Observe o cabelo marrom do personagem. Qual expressão descreve essa característica?",alternatives:[{id:"A",text:"black hair"},{id:"B",text:"brown hands"},{id:"C",text:"brown hair"},{id:"D",text:"green eyes"}],answer:{id:"C",text:"brown hair"},media:"Imagem de personagem fictício com brown hair; não usar características físicas como estereótipo identitário. Formato sugerido: Imagem → expressão.",format:"Imagem → expressão.",visualQuery:"brown hair",listenText:"",mechanic:"drag-drop",topic:"BODY DESCRIPTION"}
]});})();
