/* DUDUQ English Year 3 — Module 01
   Source: DUDUQ_Ingles_1ao5(20260825-012151).docx — Revisão Pedagógica Integral v2.2
   Thin content: no mechanic/layout/runtime patch.
*/
(function(){"use strict";
const F=window.DuduQYear3Factory;
if(!F) throw new Error("DuduQYear3Factory não carregado.");
F.publish({module:1,version:"1.0.0-scale-bootstrap",title:"Greetings, Friends & Personal Information",objective:"Participar de pequenas interações sociais, apresentar um amigo e compreender informações pessoais simples em perfis fictícios.",items:[
{id:"EN3-M1-01",status:"Ajustar",difficulty:"Fácil",skill:"Escuta / compreensão pragmática",ability:"Reconhecer uma resposta social adequada em um primeiro encontro.",prompt:"Ouça o início de um diálogo: “Hi, I’m Mia.” Qual resposta é adequada ao conhecer a pessoa?",alternatives:[{id:"A",text:"Nice to meet you."},{id:"B",text:"Good night."},{id:"C",text:"I am ten years old."},{id:"D",text:"It is a pencil."}],answer:{id:"A",text:"Nice to meet you."},media:"Áudio EN obrigatório do mini diálogo; personagens fictícios. Formato sugerido: Diálogo interativo.",format:"Diálogo interativo.",visualQuery:"Nice to meet you",listenText:"Hi, I’m Mia.",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-02",status:"Ajustar",difficulty:"Fácil",skill:"Leitura + produção guiada",ability:"Completar uma apresentação simples de outra pessoa.",prompt:"Observe Leo ao lado de Mia. Complete a apresentação: “This is my ___, Mia.”",alternatives:[{id:"A",text:"teacher"},{id:"B",text:"friend"},{id:"C",text:"pencil"},{id:"D",text:"Monday"}],answer:{id:"B",text:"friend"},media:"Imagem de dois personagens fictícios, com Mia indicada pelo nome. Formato sugerido: Sentence builder / escolha.",format:"Sentence builder / escolha.",visualQuery:"friends",listenText:"",mechanic:"drag-drop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-03",status:"Reescrever",difficulty:"Fácil",skill:"Compreensão pragmática",ability:"Escolher um cumprimento adequado ao período da manhã.",prompt:"Maya chega à escola pela manhã. Qual cumprimento combina com a situação?",alternatives:[{id:"A",text:"Good morning!"},{id:"B",text:"Good afternoon!"},{id:"C",text:"Good night!"},{id:"D",text:"See you later!"}],answer:{id:"A",text:"Good morning!"},media:"Imagem de chegada à escola pela manhã; áudio EN das opções sob toque. Formato sugerido: Cena → fala.",format:"Cena → fala.",visualQuery:"good morning",listenText:"",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-04",status:"Ajustar",difficulty:"Média",skill:"Leitura / compreensão pragmática",ability:"Selecionar a pergunta de soletração adequada a uma situação comunicativa.",prompt:"Maya quer saber como escrever o nome “Leo”. Qual pergunta ela faz?",alternatives:[{id:"A",text:"How do you spell Leo?"},{id:"B",text:"How old is Leo?"},{id:"C",text:"Where is Leo from?"},{id:"D",text:"What is Leo’s favorite toy?"}],answer:{id:"A",text:"How do you spell Leo?"},media:"Mini diálogo com personagens fictícios. Formato sugerido: Diálogo interativo.",format:"Diálogo interativo.",visualQuery:"Leo",listenText:"",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-05",status:"Manter",difficulty:"Fácil",skill:"Escuta",ability:"Identificar letras do alfabeto.",prompt:"Ouça a letra e selecione-a.",alternatives:[{id:"A",text:"N"},{id:"B",text:"M"},{id:"C",text:"S"},{id:"D",text:"B"}],answer:{id:"B",text:"M"},media:"Áudio EN obrigatório: letra M. Formato sugerido: Escuta + escolha.",format:"Escuta + escolha.",visualQuery:"M",listenText:"M",mechanic:"target-shooter",topic:"ALPHABET"},
{id:"EN3-M1-06",status:"Reescrever",difficulty:"Fácil",skill:"Leitura",ability:"Localizar o nome em uma ficha pessoal fictícia curta.",prompt:"Leia a minificha fictícia: “Name: Maya | Age: 9 | Birthday: May 12 | Favorite animal: dog”. Qual é o nome da personagem?",alternatives:[{id:"A",text:"Maya"},{id:"B",text:"9"},{id:"C",text:"May 12"},{id:"D",text:"dog"}],answer:{id:"A",text:"Maya"},media:"Minificha visual fictícia; não coletar dados reais do estudante. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"Maya profile",listenText:"",mechanic:"bubble-pop",topic:"PERSONAL INFORMATION"},
{id:"EN3-M1-07",status:"Reescrever",difficulty:"Fácil",skill:"Leitura",ability:"Localizar e compreender a idade em uma ficha pessoal fictícia.",prompt:"Leia a minificha fictícia: “Name: Maya | Age: 9 | Birthday: May 12 | Favorite animal: dog”. How old is Maya?",alternatives:[{id:"A",text:"She is 8."},{id:"B",text:"She is 9."},{id:"C",text:"She is 10."},{id:"D",text:"She is 12."}],answer:{id:"B",text:"She is 9."},media:"Minificha visual fictícia; áudio EN opcional da pergunta. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"9",listenText:"How old is Maya?",mechanic:"bubble-pop",topic:"PERSONAL INFORMATION"},
{id:"EN3-M1-08",status:"Reescrever",difficulty:"Média",skill:"Leitura",ability:"Localizar a data de aniversário em uma ficha curta.",prompt:"Leia a minificha fictícia: “Name: Maya | Age: 9 | Birthday: May 12 | Favorite animal: dog”. When is Maya’s birthday?",alternatives:[{id:"A",text:"May 12"},{id:"B",text:"May 9"},{id:"C",text:"June 12"},{id:"D",text:"March 12"}],answer:{id:"A",text:"May 12"},media:"Minificha visual fictícia; sem solicitar data real do estudante. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"Maya profile",listenText:"",mechanic:"bubble-pop",topic:"PERSONAL INFORMATION"},
{id:"EN3-M1-09",status:"Reescrever",difficulty:"Média",skill:"Leitura",ability:"Localizar uma preferência em uma ficha pessoal fictícia.",prompt:"Leia a minificha fictícia: “Name: Maya | Age: 9 | Birthday: May 12 | Favorite animal: dog”. What is Maya’s favorite animal?",alternatives:[{id:"A",text:"cat"},{id:"B",text:"dog"},{id:"C",text:"rabbit"},{id:"D",text:"bird"}],answer:{id:"B",text:"dog"},media:"Minificha visual fictícia; sem telefone, endereço ou dados familiares reais. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"dog",listenText:"",mechanic:"bubble-pop",topic:"PERSONAL INFORMATION"},
{id:"EN3-M1-10",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Compreender uma frase de apresentação de colega.",prompt:"Observe Leo apresentando Mia. Qual frase combina com a cena?",alternatives:[{id:"A",text:"This is my teacher, Leo."},{id:"B",text:"This is my cousin, Leo."},{id:"C",text:"This is my brother, Leo."},{id:"D",text:"This is my friend, Mia."}],answer:{id:"D",text:"This is my friend, Mia."},media:"Imagem de dois personagens fictícios com nomes visíveis. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"friends",listenText:"",mechanic:"drag-drop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-11",status:"Ajustar",difficulty:"Média",skill:"Leitura / compreensão pragmática",ability:"Selecionar uma resposta adequada a “Nice to meet you”.",prompt:"Complete o diálogo: “Nice to meet you.” — “___”",alternatives:[{id:"A",text:"Nice to meet you too."},{id:"B",text:"Goodbye, see you tomorrow."},{id:"C",text:"I’m nine years old."},{id:"D",text:"My favorite toy is a ball."}],answer:{id:"A",text:"Nice to meet you too."},media:"Áudio EN recomendado do mini diálogo. Formato sugerido: Diálogo interativo.",format:"Diálogo interativo.",visualQuery:"Nice to meet you",listenText:"Nice to meet you.",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-12",status:"Reescrever",difficulty:"Média",skill:"Escuta",ability:"Compreender nomes de letras em inglês para identificar uma palavra de saudação soletrada.",prompt:"Ouça as letras em inglês: “H – E – L – L – O”. Qual palavra foi soletrada?",alternatives:[{id:"A",text:"HELLO"},{id:"B",text:"HLELO"},{id:"C",text:"HELLOO"},{id:"D",text:"HELOL"}],answer:{id:"A",text:"HELLO"},media:"Áudio EN obrigatório: nomes das letras H, E, L, L, O, com pausas naturais; não exibir as letras durante a primeira escuta. Formato sugerido: Escuta + letras móveis.",format:"Escuta + letras móveis.",visualQuery:"hello",listenText:"H. E. L. L. O.",mechanic:"target-shooter",topic:"ALPHABET & SPELLING"},
{id:"EN3-M1-13",status:"Reescrever",difficulty:"Difícil",skill:"Leitura / interação",ability:"Responder a uma pergunta social simples sobre bem-estar.",prompt:"Complete o diálogo: “How are you?” — “___”",alternatives:[{id:"A",text:"I’m fine, thanks."},{id:"B",text:"See you later."},{id:"C",text:"Good morning."},{id:"D",text:"How do you spell Leo?"}],answer:{id:"A",text:"I’m fine, thanks."},media:"Áudio EN recomendado do mini diálogo. Formato sugerido: Diálogo interativo.",format:"Diálogo interativo.",visualQuery:"How are you",listenText:"How are you?",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-14",status:"Reescrever",difficulty:"Difícil",skill:"Compreensão pragmática",ability:"Selecionar uma despedida amigável adequada ao fim de uma interação.",prompt:"A conversa terminou e os personagens vão embora. Qual fala combina com a cena?",alternatives:[{id:"A",text:"See you later!"},{id:"B",text:"Good morning!"},{id:"C",text:"Nice to meet you!"},{id:"D",text:"How are you?"}],answer:{id:"A",text:"See you later!"},media:"Cena de despedida + áudio EN das opções sob toque. Formato sugerido: Cena → fala.",format:"Cena → fala.",visualQuery:"see you",listenText:"",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"},
{id:"EN3-M1-15",status:"Reescrever",difficulty:"Difícil",skill:"Compreensão pragmática",ability:"Usar um cumprimento adequado ao período da tarde em um mini diálogo.",prompt:"Mia encontra Leo à tarde e diz: “Good afternoon, Leo!” Qual resposta combina?",alternatives:[{id:"A",text:"Good afternoon, Mia!"},{id:"B",text:"Good night, Mia!"},{id:"C",text:"See you later, Mia!"},{id:"D",text:"I’m nine years old."}],answer:{id:"A",text:"Good afternoon, Mia!"},media:"Áudio EN recomendado do mini diálogo; cena de tarde. Formato sugerido: Diálogo interativo.",format:"Diálogo interativo.",visualQuery:"good afternoon",listenText:"Good afternoon, Leo!",mechanic:"bubble-pop",topic:"GREETINGS & PERSONAL INFORMATION"}
]});
})();
