/* DUDUQ YEAR 1 — MODULE 03 — official v2.3 homologation / Canary R146 */
(function(){
"use strict";
window.DUDUQ_CONTENT=window.DUDUQ_CONTENT||{};window.DUDUQ_CONTENT.english=window.DUDUQ_CONTENT.english||{};window.DUDUQ_CONTENT.english.year1=window.DUDUQ_CONTENT.english.year1||{};
const PROFILE="Y1_EARLY_LITERACY",PIN="f0f8bed8e8c24fad4eae204bf4a5cc84a8d8263f";
function image(key){const d=window.DuduQAssets?.resolveImageDetails?.(key),u=d?.url||window.DuduQAssets?.resolveImage?.(key)||"";if(!u)throw new Error(`[DuduQ Y1 M03] Asset canônico não resolvido: ${key}`);return u}
function audio(id,text){return{id,spokenText:text,speechLocale:"en-US",audioDescription:`Ouvir: ${text}`,alt:`Opção de áudio ${id}`}}
function base(s){return{id:s.id,subject:"english",year:1,module:3,skill:{code:null,description:s.skill},difficulty:s.difficulty,statement:s.statement,instruction:s.instruction,contentLanguage:"en",instructionLanguage:"pt-BR",feedbackLanguage:"pt-BR",...(s.audio?{audio:{enabled:true,text:s.audio,language:"en-US",role:"stimulus"}}:{}),alternatives:s.alternatives.map((text,i)=>({id:"ABC"[i],text})),answer:{type:"single",value:s.answer},feedback:{correct:"Muito bem! Você reconheceu a opção correta.",incorrect:"Ouça novamente, observe a pista visual e tente outra vez.",language:"pt-BR"},metadata:{screenTitle:s.topic,activityTitle:s.topic,sourceStatus:s.status,sourceSkill:"Compreensão multimodal",sourceStatement:s.statement,sourceAlternatives:s.alternatives.map((text,i)=>({id:"ABC"[i],text})),sourceAnswer:{id:s.answer,text:s.alternatives["ABC".indexOf(s.answer)]},sourceMedia:s.media,sourceSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",pedagogySpecification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",literacyDemand:"R0",readingEssential:false,yearProfile:PROFILE,instructionAudioFallback:{enabled:true,language:"pt-BR",text:s.instruction,mode:"speech-synthesis-or-recorded"},modalityAdaptation:"R0 multimodal; contrato homologado M03",canonicalAssetsRequired:true}}}
function dd(s,key,alt,semantic,visualComposition){const q=base(s),targetId=`${s.id}-answer-target`;q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",items:s.alternatives.map((text,i)=>{const id="ABC"[i];return{id,label:String(i+1),...audio(id,text),required:id===s.answer,...(id===s.answer?{targetId}:{})}}),targets:[{id:targetId,label:"",imageAsset:key,image:{src:image(key),alt},alt,capacity:1,kind:"box"}]};q.metadata.dragDropChoice={singleEditorialAnswer:s.answer,visibleLabels:"numeric-only",optionAudioRequired:true,correctTargetId:targetId,contextType:semantic,contextSemantic:semantic,visualComposition:visualComposition||null,noProceduralAsset:true};return q}
function ts(s){const q=base(s);q.delivery={mechanic:"target-shooter",preferred:["target-shooter"],blocked:["smart-sentence"],allowImage:false,allowAudio:true};q.metadata.targetShooter={audioText:"purple",mode:"audio-to-visual",shape:"balloon",correctIds:["B"],difficulty:{speed:.26,objectCount:3,spawnIntervalMs:950,requiredCorrect:1,targetSize:190,timeLimitMs:0,timerMode:"none"},items:[{id:"A",label:"A",display:"word",accent:"#F58220",semanticLabel:"orange",accessibleLabel:"cor orange"},{id:"B",label:"B",display:"word",accent:"#7E22CE",semanticLabel:"purple",accessibleLabel:"cor purple"},{id:"C",label:"C",display:"word",accent:"#EC4899",semanticLabel:"pink",accessibleLabel:"cor pink"}]};q.metadata.m03VisualComposition={helper:"M03VisualComposition",questionId:"EN1-M3-09",type:"target-shooter-accent-swatches",failClosed:true,visibleColorWords:false};return q}
const specs=[
["EN1-M3-01","easy","Identificar cores em inglês.","Observe a cor da imagem e ouça as opções em inglês e toque no áudio que nomeia corretamente o que você vê.","Observe a cor, ouça os três cards e arraste o áudio correto.",["green","red","yellow"],"B","Ajustar — Fácil","COLORS","Imagem obrigatória: bloco na cor red.","red","Bloco visual vermelho","red"],
["EN1-M3-02","easy","Identificar cores em inglês.","Ouça as opções em inglês e toque no áudio que nomeia corretamente a cor mostrada.","Observe a cor, ouça os três cards e arraste o áudio correto.",["red","green","blue"],"C","Ajustar — Fácil","COLORS","Imagem obrigatória: bloco na cor blue.","blue","Bloco visual azul","blue"],
["EN1-M3-03","easy","Identificar cores em inglês.","Observe a cor e ouça as opções. Toque no áudio que nomeia a cor mostrada.","Observe a cor, ouça os três cards e arraste o áudio correto.",["yellow","red","green"],"A","Ajustar — Fácil","COLORS","Imagem obrigatória: bloco na cor yellow.","yellow","Bloco visual amarelo","yellow"],
["EN1-M3-04","easy","Identificar cores em inglês.","A imagem destaca uma cor. Ouça as opções em inglês e toque no áudio correto.","Observe a cor, ouça os três cards e arraste o áudio correto.",["red","green","yellow"],"B","Ajustar — Fácil","COLORS","Imagem obrigatória: bloco na cor green.","green","Bloco visual verde","green"],
["EN1-M3-05","easy","Identificar objetos escolares em inglês.","Observe o objeto e ouça as opções em inglês e toque no áudio que nomeia corretamente o que você vê.","Observe o objeto, ouça os três cards e arraste o áudio correto.",["eraser","colored pencil","pencil"],"C","Ajustar — Fácil","SCHOOL OBJECTS","Imagem obrigatória: pencil.","pencil","Lápis escolar","pencil"],
["EN1-M3-06","easy","Identificar objetos escolares em inglês.","Ouça as opções em inglês e toque no áudio que nomeia corretamente o objeto da imagem.","Observe o objeto, ouça os três cards e arraste o áudio correto.",["eraser","pencil","colored pencil"],"A","Ajustar — Fácil","SCHOOL OBJECTS","Imagem obrigatória: eraser.","eraser","Borracha escolar","eraser"],
["EN1-M3-07","easy","Identificar objetos escolares em inglês.","Ouça as opções e toque no áudio que corresponde ao objeto.","Observe o objeto, ouça os três cards e arraste o áudio correto.",["eraser","ruler","pencil"],"B","Ajustar — Fácil","SCHOOL OBJECTS","Imagem obrigatória: ruler.","ruler","Régua escolar","ruler"],
["EN1-M3-08","easy","Identificar objetos escolares em inglês.","A imagem mostra um objeto escolar. Ouça as opções e toque no áudio correspondente.","Observe o objeto, ouça os três cards e arraste o áudio correto.",["eraser","pencil","backpack"],"C","Ajustar — Fácil","SCHOOL OBJECTS","Imagem obrigatória: backpack.","backpack","Mochila escolar","backpack"]
];
function S(r){return{id:r[0],difficulty:r[1],skill:r[2],statement:r[3],instruction:r[4],alternatives:r[5],answer:r[6],status:r[7],topic:r[8],media:r[9]}}
const questions=specs.map(r=>dd(S(r),r[10],r[11],r[12]));
questions.push(ts({id:"EN1-M3-09",difficulty:"medium",skill:"Identificar cores em inglês por escuta e discriminação visual.",statement:"Ouça a cor em inglês e toque no alvo visual correspondente.",instruction:"Ouça e toque no alvo da cor correspondente.",alternatives:["orange","purple","pink"],answer:"B",status:"Ajustar — Média",topic:"COLORS",media:"Áudio obrigatório: purple. Alvos visuais orange, purple e pink; sem palavras de cor visíveis.",audio:"purple"}));
questions.push(dd({id:"EN1-M3-10",difficulty:"medium",skill:"Relacionar quantidade e objeto escolar em uma expressão curta.",statement:"Observe a imagem com três réguas. Ouça as opções antes de responder.",instruction:"Observe as réguas, ouça os três cards e arraste o áudio correto.",alternatives:["two rulers","three rulers","five rulers"],answer:"B",status:"Ajustar — Média",topic:"NUMBERS",media:"Contexto obrigatório: exatamente três réguas canônicas bem separadas."},"ruler","três réguas","three rulers",{helper:"M03VisualComposition",count:3,source:"same-canonical-ruler-src"}));
questions.push(dd({id:"EN1-M3-11",difficulty:"medium",skill:"Relacionar cor e objeto escolar em uma expressão curta.",statement:"Observe o giz de cera laranja. Ouça as opções antes de responder.",instruction:"Observe o objeto, ouça os três cards e arraste o áudio correto.",alternatives:["orange crayon","pink crayon","orange pencil"],answer:"A",status:"Reescrever — Média",topic:"COLORS",media:"Imagem obrigatória: orange crayon."},"orange crayon","Giz de cera laranja","orange crayon"));
questions.push(dd({id:"EN1-M3-12",difficulty:"hard",skill:"Relacionar cor e objeto escolar em uma expressão curta.",statement:"Observe o estojo rosa. Ouça as opções antes de responder.",instruction:"Observe o objeto, ouça os três cards e arraste o áudio correto.",alternatives:["pink pencil case","purple pencil case","pink backpack"],answer:"A",status:"Reescrever — Difícil",topic:"COLORS",media:"Imagem obrigatória: pink pencil case."},"pink pencil case","Estojo rosa","pink pencil case"));
const moduleDefinition={id:"duduq-english-y1-module-03",version:"2.3.0-homolog-r146",subject:"english",year:1,module:3,title:"Colors & School Objects",description:"Year 1 early-literacy homologation build aligned to the closed M03 multimodal contract.",estimatedMinutes:5,intro:{companyKicker:"UMA CRIAÇÃO DE",companyLogo:"https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/main/Imagens%20Ilustrativa/LOGO%20DA%20EMPRESA_COLORIDO.png",companyAlt:"Editora Brasil Cultural",companyName:"Editora Brasil Cultural",companyWidth:820,collectionLogo:"https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/main/Imagens%20Ilustrativa/Logo%20EduQ%20Play.png",collectionName:"EduQ Play",collectionAlt:"EduQ Play",collectionWidth:760,loadingLabel:"PREPARANDO SUA MISSÃO",readyLabel:"MISSÃO PRONTA",startLabel:"INICIAR MISSÃO",hint:"Tudo pronto para começar!",minDurationMs:2200,brandingDurationMs:3000,switchingDurationMs:760,missionMinDurationMs:1200,sparkCount:14},pedagogyPolicy:{specification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",contentSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",profile:PROFILE,readingDefault:"R0",readingMax:"R1_NONESSENTIAL_ONLY",smartSentenceScored:false,audioRepeatable:true,imagesLargeUnambiguous:true,autonomousEnglishReadingRequired:false},visualCompositionPolicy:{helper:"M03VisualComposition",localOnly:true,failClosed:true,q09:"accent-based Target Shooter swatches; no color words visible",q10:"three DOM instances of the same canonical ruler src; decorative copies hidden from accessibility"},factory:{tag:"official-y1-m03-v2.3-r146",cleanBuild:true,artifactReuse:false,stalePayloadReuse:false,engine:"Canary R146",core:"1.0.11",targetShooter:"1.0.21",dragDrop:"2.0.24",integration:"Universal Loader / Player / canonical Assets resolver / local M03 visual composition",assetCatalog:`Assets-DuduQ canonical schema 2 @ ${PIN}`},activities:questions.map((q,i)=>({id:`Y1-M03-A${String(i+1).padStart(2,"0")}`,title:q.metadata.activityTitle,mechanic:q.delivery.mechanic,skill:{description:q.skill.description},questions:[q]})),extension:{scored:false,type:"modeled-speaking",instruction:"Ouça uma cor ou objeto, repita e aponte para o exemplo visual correspondente."}};
window.DUDUQ_CONTENT.english.year1.module03=Object.freeze(moduleDefinition);
})();