/* DUDUQ YEAR 1 — MODULE 04 — official v2.3 homologation / Canary R146 */
(function(){
"use strict";
window.DUDUQ_CONTENT=window.DUDUQ_CONTENT||{};window.DUDUQ_CONTENT.english=window.DUDUQ_CONTENT.english||{};window.DUDUQ_CONTENT.english.year1=window.DUDUQ_CONTENT.english.year1||{};
const PROFILE="Y1_EARLY_LITERACY",PIN="f0f8bed8e8c24fad4eae204bf4a5cc84a8d8263f";
const ASSET=Object.freeze({
  comeIn:"boy crianca chegando child arriving arrival",
  sitDown:"classroom command sit down sentar",
  standUp:"classroom command stand up em pe",
  quiet:"classroom command quiet silencio",
  head:"body part touch head tocar cabeca",
  hands:"body part touch hands tocar maos",
  legsSource:"body part touch knees tocar joelhos",
  arms:"body part touch arms tocar bracos",
  feet:"body part touch feet tocar pes"
});
function image(key){const d=window.DuduQAssets?.resolveImageDetails?.(key),u=d?.url||window.DuduQAssets?.resolveImage?.(key)||"";if(!u)throw new Error(`[DuduQ Y1 M04] Asset canônico não resolvido: ${key}`);return u}
function visual(id,key,alt,semantic){const u=image(key);return{id,label:id,display:"image",imageAsset:key,imageAssetKey:key,imageUrl:u,image:u,alt,semanticLabel:semantic,accessibleLabel:alt}}
function audioCard(id,text){return{id,label:id,spokenText:text,speechLocale:"en-US",audioDescription:`Ouvir: ${text}`,alt:`Opção de áudio ${id}`}}
function base(s){return{id:s.id,subject:"english",year:1,module:4,skill:{code:null,description:s.skill},difficulty:s.difficulty,statement:s.statement,instruction:s.instruction,contentLanguage:"en",instructionLanguage:"pt-BR",feedbackLanguage:"pt-BR",...(s.audio?{audio:{enabled:true,text:s.audio,language:"en-US",role:"stimulus"}}:{}),alternatives:s.alternatives.map((text,i)=>({id:"ABC"[i],text})),answer:{type:"single",value:s.answer},feedback:{correct:"Muito bem! Você reconheceu a opção correta.",incorrect:"Ouça novamente, observe a pista e tente outra vez.",language:"pt-BR"},metadata:{screenTitle:s.topic,activityTitle:s.topic,sourceStatus:s.status,sourceSkill:s.sourceSkill,sourceStatement:s.statement,sourceAlternatives:s.alternatives.map((text,i)=>({id:"ABC"[i],text})),sourceAnswer:{id:s.answer,text:s.alternatives["ABC".indexOf(s.answer)]},sourceMedia:s.media,sourceSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",pedagogySpecification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",literacyDemand:"R0",readingEssential:false,yearProfile:PROFILE,instructionAudioFallback:{enabled:true,language:"pt-BR",text:s.instruction,mode:"speech-synthesis-or-recorded"},modalityAdaptation:"R0 multimodal; conteúdo, ordem, alternativas, resposta e habilidade oficiais preservados",canonicalAssetsRequired:true}}}
function ts(s,items){const q=base(s);q.delivery={mechanic:"target-shooter",preferred:["target-shooter"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.metadata.targetShooter={audioText:s.audio||"",mode:"audio-to-image",shape:"balloon",correctIds:[s.answer],difficulty:{speed:.26,objectCount:items.length,spawnIntervalMs:950,requiredCorrect:1,targetSize:190,timeLimitMs:0,timerMode:"none"},items};return q}
function ddAudio(s,key,alt,semantic,composition){const q=base(s),targetId=`${s.id}-answer-target`;q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",items:s.alternatives.map((text,i)=>{const id="ABC"[i];return{...audioCard(id,text),label:String(i+1),required:id===s.answer,...(id===s.answer?{targetId}:{})}}),targets:[{id:targetId,label:"",imageAsset:key,image:{src:image(key),alt},alt,capacity:1,kind:"box"}]};q.metadata.dragDropChoice={singleEditorialAnswer:s.answer,visibleLabels:"numeric-only",optionAudioRequired:true,correctTargetId:targetId,contextType:"canonical-body-context",contextSemantic:semantic,visualComposition:composition||null,noProceduralAsset:true};return q}
function ddCourtesy(s){const q=base(s),targetId=`${s.id}-answer-target`,sit=visual("B",ASSET.sitDown,"Cena de criança sentada — comando sit down","sit down");q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",items:[{...audioCard("A","please"),label:"1",required:false},{id:"B",label:"2",required:false,imageAsset:sit.imageAsset,imageAssetKey:sit.imageAssetKey,imageUrl:sit.imageUrl,image:{src:sit.imageUrl,alt:sit.alt},alt:sit.alt},{...audioCard("C","thank you"),label:"3",required:true,targetId}],targets:[{id:targetId,label:"",spokenText:"Thank you",speechLocale:"en-US",audioDescription:"Ouvir novamente: Thank you",alt:"Destino com áudio repetível da expressão ouvida",capacity:1,kind:"box"}]};q.metadata.dragDropChoice={singleEditorialAnswer:"C",visibleLabels:"numeric-only",optionAudioRequired:"mixed-audio-context",correctTargetId:targetId,contextType:"repeatable-audio-prompt",contextSemantic:"thank you",noProceduralAsset:true};q.metadata.courtesyChoice={promptTextHidden:true,answerWordsHiddenBeforeResponse:true,visualDistractorAsset:ASSET.sitDown,mixedModalities:["audio","image","audio"]};return q}
const q01=ts({id:"EN1-M4-01",difficulty:"easy",skill:"Compreender comandos usados em sala de aula.",statement:"Ouça o comando e escolha a expressão que você ouviu.",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["come in","sit down","stand up"],answer:"B",status:"Ajustar — Fácil",sourceSkill:"Escuta",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: sit down. Formato: áudio → imagem/cena; leitura não necessária.",audio:"sit down"},[visual("A",ASSET.comeIn,"Criança chegando e entrando — comando come in","come in"),visual("B",ASSET.sitDown,"Criança sentada — comando sit down","sit down"),visual("C",ASSET.standUp,"Criança em pé — comando stand up","stand up")]);
const q02=ts({id:"EN1-M4-02",difficulty:"easy",skill:"Compreender comandos usados em sala de aula.",statement:"Escute com atenção. Qual comando foi dito?",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["come in","sit down","stand up"],answer:"C",status:"Ajustar — Fácil",sourceSkill:"Escuta",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: stand up. Formato: áudio → imagem/cena; leitura não necessária.",audio:"stand up"},[visual("A",ASSET.comeIn,"Criança chegando e entrando — comando come in","come in"),visual("B",ASSET.sitDown,"Criança sentada — comando sit down","sit down"),visual("C",ASSET.standUp,"Criança em pé — comando stand up","stand up")]);
const q03=ts({id:"EN1-M4-03",difficulty:"easy",skill:"Compreender comandos usados em sala de aula.",statement:"Toque no cartão que corresponde ao comando ouvido.",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["come in","sit down","stand up"],answer:"A",status:"Ajustar — Fácil",sourceSkill:"Escuta",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: come in. Formato: áudio → imagem/cena; leitura não necessária.",audio:"come in"},[visual("A",ASSET.comeIn,"Criança chegando e entrando — comando come in","come in"),visual("B",ASSET.sitDown,"Criança sentada — comando sit down","sit down"),visual("C",ASSET.standUp,"Criança em pé — comando stand up","stand up")]);
const q04=ts({id:"EN1-M4-04",difficulty:"easy",skill:"Compreender comandos e chunks frequentes da rotina de sala.",statement:"Ouça o comando e selecione a expressão que você ouviu.",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["come in","Quiet, please.","sit down"],answer:"B",status:"Ajustar — Fácil",sourceSkill:"Escuta",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: Quiet, please. Voz natural e acolhedora; leitura não necessária.",audio:"Quiet, please."},[visual("A",ASSET.comeIn,"Criança chegando e entrando — comando come in","come in"),visual("B",ASSET.quiet,"Gesto de silêncio — comando Quiet, please.","quiet please"),visual("C",ASSET.sitDown,"Criança sentada — comando sit down","sit down")]);
const q05=ddAudio({id:"EN1-M4-05",difficulty:"easy",skill:"Identificar partes do corpo humano em inglês.",statement:"Observe a parte do corpo destacada e ouça as opções em inglês e toque no áudio que nomeia corretamente o que você vê.",instruction:"Observe a imagem, ouça os três cards e arraste o áudio correto.",alternatives:["hands","legs","head"],answer:"C",status:"Ajustar — Fácil",sourceSkill:"Compreensão multimodal",topic:"BODY",media:"Imagem obrigatória: corpo com destaque em head. Imagem/contexto → áudio; leitura não necessária."},ASSET.head,"Cabeça destacada no corpo","head");
const q06=ddAudio({id:"EN1-M4-06",difficulty:"easy",skill:"Identificar partes do corpo humano em inglês.",statement:"Observe a parte do corpo destacada. Ouça as opções em inglês e toque no áudio correspondente.",instruction:"Observe a imagem, ouça os três cards e arraste o áudio correto.",alternatives:["hands","head","legs"],answer:"A",status:"Ajustar — Fácil",sourceSkill:"Compreensão multimodal",topic:"BODY",media:"Imagem obrigatória: corpo com destaque em hands. Imagem/contexto → áudio; leitura não necessária."},ASSET.hands,"Mãos destacadas no corpo","hands");
const q07=ddAudio({id:"EN1-M4-07",difficulty:"easy",skill:"Identificar partes do corpo humano em inglês.",statement:"Toque no cartão que nomeia a parte do corpo destacada. Ouça as opções antes de responder.",instruction:"Observe as pernas destacadas, ouça os três cards e arraste o áudio correto.",alternatives:["head","legs","hands"],answer:"B",status:"Ajustar — Fácil",sourceSkill:"Compreensão multimodal",topic:"BODY",media:"Imagem obrigatória: corpo com destaque inequívoco em legs. Asset corporal canônico + composição local fail-closed; leitura não necessária."},ASSET.legsSource,"Corpo com pernas destacadas","legs",{helper:"M04VisualComposition",type:"canonical-body-local-legs-highlight",sourceAsset:ASSET.legsSource,failClosed:true});
const q08=ddAudio({id:"EN1-M4-08",difficulty:"easy",skill:"Identificar partes do corpo humano em inglês.",statement:"Observe a parte do corpo destacada. Ouça as opções em inglês e toque no áudio correspondente.",instruction:"Observe a imagem, ouça os três cards e arraste o áudio correto.",alternatives:["head","hands","arms"],answer:"C",status:"Ajustar — Fácil",sourceSkill:"Compreensão multimodal",topic:"BODY",media:"Imagem obrigatória: corpo com destaque em arms. Imagem/contexto → áudio; leitura não necessária."},ASSET.arms,"Braços destacados no corpo","arms");
const q09=ddAudio({id:"EN1-M4-09",difficulty:"easy",skill:"Identificar partes do corpo humano em inglês.",statement:"Qual opção identifica corretamente a parte do corpo indicada? Ouça as opções antes de responder.",instruction:"Observe a imagem, ouça os três cards e arraste o áudio correto.",alternatives:["feet","head","hands"],answer:"A",status:"Ajustar — Fácil",sourceSkill:"Compreensão multimodal",topic:"BODY",media:"Imagem obrigatória: corpo com destaque em feet. Imagem/contexto → áudio; leitura não necessária."},ASSET.feet,"Pés destacados no corpo","feet");
const q10=ts({id:"EN1-M4-10",difficulty:"medium",skill:"Executar/compreender o comando Touch your....",statement:"Ouça “Touch your head”. Qual cartão mostra o comando ouvido?",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["Touch your hands.","Touch your head.","Touch your feet."],answer:"B",status:"Ajustar — Média",sourceSkill:"Escuta",topic:"BODY",media:"Áudio EN obrigatório: Touch your head. Áudio → imagem/cena; leitura não necessária.",audio:"Touch your head"},[visual("A",ASSET.hands,"Pessoa tocando as mãos — Touch your hands","Touch your hands"),visual("B",ASSET.head,"Pessoa tocando a cabeça — Touch your head","Touch your head"),visual("C",ASSET.feet,"Pessoa tocando os pés — Touch your feet","Touch your feet")]);
const q11=ddCourtesy({id:"EN1-M4-11",difficulty:"medium",skill:"Reconhecer auditivamente uma expressão de cortesia.",statement:"Ouça “Thank you”. Qual opção mostra a mesma expressão?",instruction:"Ouça o destino e as opções. Arraste a opção que repete a expressão ouvida.",alternatives:["please","sit down","thank you"],answer:"C",status:"Ajustar — Média",sourceSkill:"Escuta",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: Thank you. A e C são áudios sem texto antes da resposta; B é cena sit down. Leitura não necessária.",audio:"Thank you"});
const q12=ts({id:"EN1-M4-12",difficulty:"hard",skill:"Integrar comando e parte do corpo.",statement:"Ouça “Touch your feet”. Qual cartão mostra o comando ouvido?",instruction:"Ouça e toque na cena que mostra o comando.",alternatives:["Touch your feet.","Touch your hands.","Touch your arms."],answer:"A",status:"Ajustar — Difícil",sourceSkill:"Escuta",topic:"BODY",media:"Áudio EN obrigatório: Touch your feet. Áudio → imagem/cena; leitura não necessária.",audio:"Touch your feet"},[visual("A",ASSET.feet,"Pessoa tocando os pés — Touch your feet","Touch your feet"),visual("B",ASSET.hands,"Pessoa tocando as mãos — Touch your hands","Touch your hands"),visual("C",ASSET.arms,"Pessoa tocando os braços — Touch your arms","Touch your arms")]);
const questions=[q01,q02,q03,q04,q05,q06,q07,q08,q09,q10,q11,q12];
const moduleDefinition={id:"duduq-english-y1-module-04",version:"2.3.0-homolog-r146",subject:"english",year:1,module:4,title:"Classroom Commands & My Body",description:"Year 1 early-literacy homologation build aligned to official v2.3 and Factory Pedagogy v1.2.",estimatedMinutes:6,intro:{companyKicker:"UMA CRIAÇÃO DE",companyLogo:"https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/main/Imagens%20Ilustrativa/LOGO%20DA%20EMPRESA_COLORIDO.png",companyAlt:"Editora Brasil Cultural",companyName:"Editora Brasil Cultural",companyWidth:820,collectionLogo:"https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/main/Imagens%20Ilustrativa/Logo%20EduQ%20Play.png",collectionName:"EduQ Play",collectionAlt:"EduQ Play",collectionWidth:760,loadingLabel:"PREPARANDO SUA MISSÃO",readyLabel:"MISSÃO PRONTA",startLabel:"INICIAR MISSÃO",hint:"Tudo pronto para começar!",minDurationMs:2200,brandingDurationMs:3000,switchingDurationMs:760,missionMinDurationMs:1200,sparkCount:14},pedagogyPolicy:{specification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",contentSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",profile:PROFILE,readingDefault:"R0",readingMax:"R1_NONESSENTIAL_ONLY",smartSentenceScored:false,audioRepeatable:true,imagesLargeUnambiguous:true,autonomousEnglishReadingRequired:false},visualCompositionPolicy:{helper:"M04VisualComposition",localOnly:true,failClosed:true,legs:{questionId:"EN1-M4-07",canonicalSource:ASSET.legsSource,presentation:"local visual highlight over canonical body image; no generated media"},comeIn:{canonicalAsset:ASSET.comeIn,semanticCriterion:"child arriving/entry scene; not greeting-only"}},factory:{tag:"official-y1-m04-v2.3-r146",cleanBuild:true,artifactReuse:false,stalePayloadReuse:false,engine:"Canary R146",core:"1.0.11",targetShooter:"1.0.21",dragDrop:"2.0.24",integration:"Universal Loader / Player / canonical Assets resolver / local M04 visual composition",assetCatalog:`Assets-DuduQ canonical schema 2 @ ${PIN}`},activities:questions.map((q,i)=>({id:`Y1-M04-A${String(i+1).padStart(2,"0")}`,title:q.metadata.activityTitle,mechanic:q.delivery.mechanic,skill:{description:q.skill.description},questions:[q]})),extension:{scored:false,type:"teacher-says",instruction:"Ouça um comando e execute ou aponte para a ação, sem punição por tempo."}};
window.DUDUQ_CONTENT.english.year1.module04=Object.freeze(moduleDefinition);
})();