/* DUDUQ YEAR 1 — MODULE 06 — Conteúdo Oficial v2.3 / Canary R147 */
(function(){
"use strict";
window.DUDUQ_CONTENT=window.DUDUQ_CONTENT||{};window.DUDUQ_CONTENT.english=window.DUDUQ_CONTENT.english||{};window.DUDUQ_CONTENT.english.year1=window.DUDUQ_CONTENT.english.year1||{};
const PROFILE="Y1_EARLY_LITERACY",PIN="f0f8bed8e8c24fad4eae204bf4a5cc84a8d8263f";
const K=Object.freeze({morning:"good morning",hello:"hello",goodbye:"goodbye",bluePencil:"blue pencil",backpack:"backpack",orangeCrayon:"orange crayon",sitDown:"classroom command sit down sentar",standUp:"classroom command stand up em pe",hands:"body part touch hands tocar maos",feet:"body part touch feet tocar pes",head:"body part touch head tocar cabeca",arms:"body part touch arms tocar bracos",legs:"body part touch knees tocar joelhos",turtle:"turtle",redPencil:"red pencil",ruler:"ruler",dog:"dog"});
function asset(key){const d=window.DuduQAssets?.resolveImageDetails?.(key)||null,u=String(d?.url||window.DuduQAssets?.resolveImage?.(key)||"");if(!u)throw new Error(`[DuduQ Y1 M06] Asset canônico não resolvido: ${key}`);if(/^(data:|blob:)/i.test(u)||/\.svg(?:\?|$)/i.test(u))throw new Error(`[DuduQ Y1 M06] Asset não permitido: ${key}`);return Object.freeze({key,url:u,details:d})}
const R=Object.freeze(Object.fromEntries(Object.entries(K).map(([name,key])=>[name,asset(key)])));
function visual(id,name,alt,required=false,composition=null){const a=R[name];return{id,label:"",imageAsset:a.key,imageAssetKey:a.key,imageUrl:a.url,image:a.url,alt,semanticLabel:alt,accessibleLabel:alt,required,...(composition?{localComposition:composition}:{})}}
function audioCard(id,text,required,targetId){return{id,label:String("ABC".indexOf(id)+1),spokenText:text,speechLocale:"en-US",audioDescription:`Ouvir: ${text}`,alt:`Opção de áudio ${id}`,required,...(required?{targetId}:{})}}
function base(s){return{id:s.id,subject:"english",year:1,module:6,skill:{code:null,description:s.skill},difficulty:s.difficulty,statement:s.statement,instruction:s.instruction,contentLanguage:"en",instructionLanguage:"pt-BR",feedbackLanguage:"pt-BR",...(s.audio?{audio:{enabled:true,text:s.audio,spokenText:s.audio,language:"en-US",speechLocale:"en-US",role:"stimulus",repeatable:true,fallback:"speech-synthesis"}}:{}),alternatives:s.alts.map((text,i)=>({id:"ABC"[i],text})),answer:{type:"single",value:s.answer},feedback:{correct:"Muito bem!",incorrect:"Ouça novamente, observe a pista e tente outra vez.",language:"pt-BR"},metadata:{screenTitle:s.topic,activityTitle:s.topic,sourceSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",pedagogySpecification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",sourceStatement:s.statement,sourceAlternatives:s.alts.slice(),sourceAnswer:s.answer,sourceMedia:s.media,literacyDemand:"R0",readingEssential:false,yearProfile:PROFILE,instructionAudioFallback:{enabled:true,language:"pt-BR",text:s.instruction,mode:"speech-synthesis-or-recorded"},canonicalAssetsRequired:true,assetResolution:"DuduQAssets.resolveImageDetails/resolveImage",noProceduralAsset:true}}}
function dd(s,name,alt,composition=null){const q=base(s),targetId=`${s.id}-answer-target`,a=R[name];q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",options:{shuffleItems:false,shuffleTargets:false,maxAttempts:3},retry:{maxAttempts:3,wrongBehaviour:"reset-item"},items:s.alts.map((t,i)=>audioCard("ABC"[i],t,"ABC"[i]===s.answer,targetId)),targets:[{id:targetId,label:"",imageAsset:a.key,imageAssetKey:a.key,image:{src:a.url,alt},imageUrl:a.url,alt,accessibleLabel:alt,capacity:1,maxItems:1,kind:"box",...(composition?{localComposition:composition}:{})}]};q.metadata.dragDropChoice={singleEditorialAnswer:s.answer,visibleLabels:"numeric-only",optionAudioRequired:true,correctTargetId:targetId,contextSemantic:alt,canonicalAssetKey:a.key,localComposition:composition,noProceduralAsset:true};return q}
function ts(s,items){const q=base(s);q.delivery={mechanic:"target-shooter",preferred:["target-shooter"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.metadata.targetShooter={audioText:s.audio,mode:"audio-to-image",shape:"balloon",correctIds:[s.answer],difficulty:{speed:.26,objectCount:3,spawnIntervalMs:950,requiredCorrect:1,targetSize:190,timeLimitMs:0,timerMode:"none"},items};return q}
const q01=dd({id:"EN1-M6-01",difficulty:"easy",skill:"Compreender uma saudação + identificação com apoio de cena.",statement:"Cena: manhã, Leo chegando. Cartão mostra Leo. Qual opção combina com a cena? Ouça as opções antes de responder.",instruction:"Observe a cena, ouça as opções e arraste o áudio correto.",alts:["Good night! I’m Leo.","Good morning! I’m Leo.","Goodbye! I’m Leo."],answer:"B",topic:"GREETINGS",media:"Cena de manhã + personagem fictício Leo. Imagem/contexto → áudio."},"morning","Cena de chegada pela manhã",{helper:"M06VisualComposition",type:"arrival-greeting",sourceAssetKey:K.morning,failClosed:true});
const q02=ts({id:"EN1-M6-02",difficulty:"easy",skill:"Reconhecer quantidade, cor e objeto escolar em uma expressão oral.",statement:"Ouça “Six blue pencils.” Qual imagem mostra o que foi dito?",instruction:"Ouça e toque na imagem correta.",alts:["6 lápis azuis","5 lápis azuis","6 réguas azuis"],answer:"A",topic:"NUMBERS",media:"Áudio EN obrigatório: Six blue pencils. Áudio → imagem.",audio:"Six blue pencils."},[visual("A","bluePencil","Seis lápis azuis",true,{helper:"M06VisualComposition",type:"repeat-count",count:6,sourceAssetKey:K.bluePencil,failClosed:true}),visual("B","bluePencil","Cinco lápis azuis",false,{helper:"M06VisualComposition",type:"repeat-count",count:5,sourceAssetKey:K.bluePencil,failClosed:true}),visual("C","ruler","Seis réguas",false,{helper:"M06VisualComposition",type:"repeat-count",count:6,sourceAssetKey:K.ruler,failClosed:true})]);
const q03=dd({id:"EN1-M6-03",difficulty:"easy",skill:"Identificar cor + objeto escolar em uma expressão oral.",statement:"Observe a mochila vermelha. Qual opção combina com a imagem? Ouça as opções antes de responder.",instruction:"Observe a mochila, ouça as opções e arraste o áudio correto.",alts:["It’s a green backpack.","It’s a red backpack.","It’s a yellow backpack."],answer:"B",topic:"COLORS",media:"Imagem obrigatória: red backpack. Imagem/contexto → áudio."},"backpack","Mochila vermelha",{helper:"M06VisualComposition",type:"canonical-color-mask",semantic:"red backpack",color:"red",sourceAssetKey:K.backpack,failClosed:true});
const q04=dd({id:"EN1-M6-04",difficulty:"easy",skill:"Reconhecer quantidade + cor + objeto escolar.",statement:"Observe os três gizes de cera laranja. Qual expressão descreve a imagem? Ouça as opções antes de responder.",instruction:"Observe os objetos, ouça as opções e arraste o áudio correto.",alts:["Three orange crayons.","Four orange crayons.","Three blue crayons."],answer:"A",topic:"NUMBERS",media:"Imagem obrigatória: 3 orange crayons. Imagem/contexto → áudio."},"orangeCrayon","Três gizes de cera laranja",{helper:"M06VisualComposition",type:"repeat-count",count:3,sourceAssetKey:K.orangeCrayon,failClosed:true});
const q05=ts({id:"EN1-M6-05",difficulty:"easy",skill:"Compreender comando de sala de aula em inglês.",statement:"Ouça “Sit down, please.” Qual imagem mostra o comando?",instruction:"Ouça e toque na cena correta.",alts:["personagem sentado","personagem em pé","personagem chegando"],answer:"A",topic:"CLASSROOM COMMANDS",media:"Áudio EN obrigatório: Sit down, please. Áudio → imagem.",audio:"Sit down, please."},[visual("A","sitDown","Criança sentada",true),visual("B","standUp","Criança em pé"),visual("C","hello","Criança chegando",false,{helper:"M06VisualComposition",type:"arrival-greeting",sourceAssetKey:K.hello,failClosed:true})]);
const q06=ts({id:"EN1-M6-06",difficulty:"easy",skill:"Compreender comando com parte do corpo.",statement:"Ouça “Touch your hands.” Qual imagem mostra o comando?",instruction:"Ouça e toque na cena correta.",alts:["tocando os pés","tocando as mãos","tocando a cabeça"],answer:"B",topic:"BODY",media:"Áudio EN obrigatório: Touch your hands. Áudio → imagem.",audio:"Touch your hands."},[visual("A","feet","Pessoa tocando os pés"),visual("B","hands","Pessoa tocando as mãos",true),visual("C","head","Pessoa tocando a cabeça")]);
const q07=dd({id:"EN1-M6-07",difficulty:"easy",skill:"Compreender tamanho + animal em expressão oral.",statement:"Observe a tartaruga pequena. Qual descrição combina com a imagem? Ouça as opções antes de responder.",instruction:"Observe a tartaruga, ouça as opções e arraste o áudio correto.",alts:["It’s a small turtle.","It’s a big turtle.","It’s a small dog."],answer:"A",topic:"ANIMALS",media:"Imagem obrigatória: small turtle. Imagem/contexto → áudio."},"turtle","Tartaruga pequena",{helper:"M06VisualComposition",type:"canonical-small",scale:.62,sourceAssetKey:K.turtle,failClosed:true});
const q08=dd({id:"EN1-M6-08",difficulty:"easy",skill:"Identificar cor + objeto escolar em expressão oral.",statement:"Observe o lápis vermelho. Qual opção combina com a imagem? Ouça as opções antes de responder.",instruction:"Observe o lápis, ouça as opções e arraste o áudio correto.",alts:["It’s a blue pencil.","It’s a red pencil.","It’s a green pencil."],answer:"B",topic:"COLORS",media:"Imagem obrigatória: red pencil. Imagem/contexto → áudio."},"redPencil","Lápis vermelho");
const q09=ts({id:"EN1-M6-09",difficulty:"medium",skill:"Reconhecer quantidade + objeto escolar em expressão oral.",statement:"Ouça “Five rulers.” Qual imagem mostra o que foi dito?",instruction:"Ouça e toque na imagem correta.",alts:["4 réguas","5 réguas","6 réguas"],answer:"B",topic:"NUMBERS",media:"Áudio EN obrigatório: Five rulers. Áudio → imagem.",audio:"Five rulers."},[visual("A","ruler","Quatro réguas",false,{helper:"M06VisualComposition",type:"repeat-count",count:4,sourceAssetKey:K.ruler,failClosed:true}),visual("B","ruler","Cinco réguas",true,{helper:"M06VisualComposition",type:"repeat-count",count:5,sourceAssetKey:K.ruler,failClosed:true}),visual("C","ruler","Seis réguas",false,{helper:"M06VisualComposition",type:"repeat-count",count:6,sourceAssetKey:K.ruler,failClosed:true})]);
const q10=ts({id:"EN1-M6-10",difficulty:"medium",skill:"Reconhecer parte do corpo em expressão oral.",statement:"Ouça “My arms.” Qual imagem corresponde?",instruction:"Ouça e toque na imagem correta.",alts:["personagem tocando as pernas","personagem tocando os braços","personagem tocando a cabeça"],answer:"B",topic:"BODY",media:"Áudio EN obrigatório: My arms. Áudio → imagem.",audio:"My arms."},[visual("A","legs","Pessoa tocando as pernas"),visual("B","arms","Pessoa tocando os braços",true),visual("C","head","Pessoa tocando a cabeça")]);
const q11=dd({id:"EN1-M6-11",difficulty:"medium",skill:"Compreender tamanho + cor + animal em descrição oral.",statement:"Observe o cachorro grande e marrom. Qual descrição combina com a imagem? Ouça as opções antes de responder.",instruction:"Observe o cachorro, ouça as opções e arraste o áudio correto.",alts:["It’s a big brown dog.","It’s a small brown dog.","It’s a big brown cat."],answer:"A",topic:"ANIMALS",media:"Imagem obrigatória: big brown dog. Imagem/contexto → áudio."},"dog","Cachorro grande e marrom",{helper:"M06VisualComposition",type:"canonical-big-brown-mask",scale:1.16,semantic:"big brown dog",color:"brown",sourceAssetKey:K.dog,failClosed:true});
const q12=dd({id:"EN1-M6-12",difficulty:"hard",skill:"Integrar saudação, identificação e despedida em uma sequência oral curta.",statement:"Observe a sequência: Leo chega, cumprimenta e depois vai embora. Qual áudio combina com toda a sequência?",instruction:"Observe a sequência, ouça as opções e arraste o áudio correto.",alts:["Goodbye! I’m Leo.","Good morning! I’m Leo.","Good morning. I’m Leo. Goodbye!"],answer:"C",topic:"GREETINGS",media:"Sequência de duas cenas: chegada/saudação e despedida. Imagem/contexto → áudio."},"morning","Sequência: chegada pela manhã e despedida",{helper:"M06VisualComposition",type:"arrival-farewell-sequence",firstAssetKey:K.morning,secondAssetKey:K.goodbye,failClosed:true});
const questions=[q01,q02,q03,q04,q05,q06,q07,q08,q09,q10,q11,q12];
const M={id:"duduq-english-y1-module-06",version:"2.3.1-official-r147",subject:"english",year:1,module:6,title:"My English World",description:"Conteúdo Oficial v2.3 — Y1_EARLY_LITERACY R0.",estimatedMinutes:6,pedagogyPolicy:{specification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",contentSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",profile:PROFILE,readingDefault:"R0",autonomousEnglishReadingRequired:false,audioRepeatable:true},assetResolutionPolicy:{resolver:"DuduQAssets.resolveImageDetails/resolveImage",failClosed:true,manualImagePaths:false,proceduralFallback:false,pinnedCatalog:PIN},visualCompositionPolicy:{helper:"M06VisualComposition",localOnly:true,failClosed:true,proven:["repeat-count:3-orange-crayons","repeat-count:4-rulers","repeat-count:5-rulers","repeat-count:6-rulers","arrival-greeting-farewell"],localSemantic:["red-backpack:canonical-mask","small-turtle:canonical-scale","big-brown-dog:canonical-mask-scale"],globalAliasChanges:false},factory:{tag:"official-y1-m06-v2.3-r147",engine:"Canary R147",core:"1.0.12",targetShooter:"1.0.21",dragDrop:"2.0.24",assetPin:PIN},activities:questions.map((q,i)=>({id:`Y1-M06-A${String(i+1).padStart(2,"0")}`,title:q.metadata.activityTitle,mechanic:q.delivery.mechanic,skill:{description:q.skill.description},questions:[q]}))};
window.DUDUQ_CONTENT.english.year1.module06=Object.freeze(M);
})();