/* DUDUQ Y1 M05 — official v2.3 — Canary R147 */
(function(){
"use strict";
window.DUDUQ_CONTENT=window.DUDUQ_CONTENT||{};window.DUDUQ_CONTENT.english=window.DUDUQ_CONTENT.english||{};window.DUDUQ_CONTENT.english.year1=window.DUDUQ_CONTENT.english.year1||{};
const PROFILE="Y1_EARLY_LITERACY",PIN="f0f8bed8e8c24fad4eae204bf4a5cc84a8d8263f",ROOT=`https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/${PIN}/Imagens%20Ilustrativa/`;
const U=f=>ROOT+f.split("/").map(encodeURIComponent).join("/");
const A=Object.freeze({cat:U("Gato.png"),dog:U("Cachorro.png"),fish:U("peixe.png"),rabbit:U("coelho.png"),hamster:U("hamster.png"),bird:U("ave.png"),turtle:U("tartaruga.png"),bigCat:U("big cat - gato grande.png"),smallCat:U("small cat -gato pequeno.png"),bigDog:U("big dog -cachorro grande.png"),smallDog:U("small dog -cachorro pequeno.png"),person:U("boy_menino_child_boy_s4xru5.png")});
function base(s){return{id:s.id,subject:"english",year:1,module:5,skill:{code:null,description:s.skill},difficulty:s.difficulty,statement:s.statement,instruction:s.instruction,contentLanguage:"en",instructionLanguage:"pt-BR",feedbackLanguage:"pt-BR",...(s.audio?{audio:{enabled:true,text:s.audio,spokenText:s.audio,language:"en-US",speechLocale:"en-US",role:"stimulus",repeatable:true,fallback:"speech-synthesis"}}:{}),alternatives:s.alts.map((text,i)=>({id:"ABC"[i],text})),answer:{type:"single",value:s.answer},feedback:{correct:"Muito bem!",incorrect:"Ouça novamente, observe e tente outra vez.",language:"pt-BR"},metadata:{screenTitle:"PETS, COLORS & SIZE",activityTitle:"PETS, COLORS & SIZE",sourceSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",pedagogySpecification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",sourceStatement:s.statement,sourceAlternatives:s.alts,sourceAnswer:s.answer,sourceMedia:s.media,literacyDemand:"R0",readingEssential:false,yearProfile:PROFILE,instructionAudioFallback:{enabled:true,language:"pt-BR",text:s.instruction,mode:"speech-synthesis-or-recorded"},canonicalAssetsRequired:true,noProceduralAsset:true,...(s.assetStatus?{assetStatus:s.assetStatus}:{})}}}
function dd(s,v){const q=base(s),tid=`${s.id}-answer-target`;q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",options:{shuffleItems:false,shuffleTargets:false,maxAttempts:3},retry:{maxAttempts:3,wrongBehaviour:"reset-item"},items:s.alts.map((text,i)=>{const id="ABC"[i],ok=id===s.answer;return{id,label:String(i+1),spokenText:text,speechLocale:"en-US",audioDescription:`Ouvir: ${text}`,alt:`Opção de áudio ${id}`,required:ok,...(ok?{targetId:tid}:{})}}),targets:[{id:tid,label:"",image:{src:v.image,alt:v.alt},imageUrl:v.image,alt:v.alt,accessibleLabel:v.alt,capacity:1,maxItems:1,kind:"box",...(v.localComposition?{localComposition:v.localComposition}:{})}]};q.metadata.dragDropChoice={singleEditorialAnswer:s.answer,visibleLabels:"numeric-only",optionAudioRequired:true,correctTargetId:tid,contextSemantic:v.semantic,localComposition:v.localComposition||null,noProceduralAsset:true};return q}
function visual(id,image,alt,pet,required){return{id,label:"",value:pet,image,alt,accessibleLabel:alt,required,localComposition:{helper:"M05VisualComposition",type:"canonical-person-plus-pet",person:A.person,pet:image,failClosed:true}}}
function ts(s,targets){const q=base(s);q.delivery={mechanic:"target-shooter",preferred:["target-shooter"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.metadata.targetShooter={audioText:s.audio,mode:"audio-to-image",shape:"balloon",correctIds:[s.answer],difficulty:{speed:.26,objectCount:3,spawnIntervalMs:950,requiredCorrect:1,targetSize:190,timeLimitMs:0,timerMode:"none"},items:targets};return q}
const Q=[
dd({id:"EN1-M5-01",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem e ouça. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["DOG","CAT","FISH"],answer:"A",media:"Imagem: cachorro; imagem/contexto → áudio."},{image:A.dog,alt:"Cachorro",semantic:"dog"}),
dd({id:"EN1-M5-02",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["CAT","DOG","RABBIT"],answer:"A",media:"Imagem: gato; imagem/contexto → áudio."},{image:A.cat,alt:"Gato",semantic:"cat"}),
dd({id:"EN1-M5-03",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem e ouça. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["FISH","BIRD","CAT"],answer:"A",media:"Imagem: peixe; imagem/contexto → áudio."},{image:A.fish,alt:"Peixe",semantic:"fish"}),
dd({id:"EN1-M5-04",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["RABBIT","HAMSTER","DOG"],answer:"A",media:"Imagem: coelho; imagem/contexto → áudio."},{image:A.rabbit,alt:"Coelho",semantic:"rabbit"}),
dd({id:"EN1-M5-05",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["HAMSTER","BIRD","TURTLE"],answer:"A",media:"Imagem: hamster; imagem/contexto → áudio."},{image:A.hamster,alt:"Hamster",semantic:"hamster"}),
dd({id:"EN1-M5-06",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["BIRD","FISH","CAT"],answer:"A",media:"Imagem: pássaro; imagem/contexto → áudio."},{image:A.bird,alt:"Pássaro",semantic:"bird"}),
dd({id:"EN1-M5-07",difficulty:"easy",skill:"Associar big a uma representação visual de tamanho grande.",statement:"Veja as imagens e ouça. Qual é BIG?",instruction:"Veja os gatos, ouça as opções e arraste o áudio correto.",alts:["BIG","SMALL","CAT"],answer:"A",media:"Gato grande + gato pequeno; imagem/contexto → áudio."},{image:A.bigCat,alt:"Dois gatos: um grande e um pequeno",semantic:"big cat versus small cat",localComposition:{helper:"M05VisualComposition",type:"canonical-size-pair",large:A.bigCat,small:A.smallCat,failClosed:true}}),
dd({id:"EN1-M5-08",difficulty:"easy",skill:"Associar small a uma representação visual de tamanho pequeno.",statement:"Veja as imagens e ouça. Qual é SMALL?",instruction:"Veja os cachorros, ouça as opções e arraste o áudio correto.",alts:["SMALL","BIG","DOG"],answer:"A",media:"Cachorro grande + cachorro pequeno; imagem/contexto → áudio."},{image:A.bigDog,alt:"Dois cachorros: um grande e um pequeno",semantic:"big dog versus small dog",localComposition:{helper:"M05VisualComposition",type:"canonical-size-pair",large:A.bigDog,small:A.smallDog,failClosed:true}}),
dd({id:"EN1-M5-09",difficulty:"medium",skill:"Associar brown à representação visual de um cachorro marrom.",statement:"Veja a imagem. Qual é a opção correta?",instruction:"Veja o cachorro, ouça as opções e arraste o áudio correto.",alts:["BROWN DOG","WHITE DOG","BLACK DOG"],answer:"A",media:"Imagem obrigatória: cachorro marrom; imagem/contexto → áudio.",assetStatus:"CANONICAL_DIRECT_VISUAL_GATE"},{image:A.dog,alt:"Cachorro marrom",semantic:"brown dog"}),
dd({id:"EN1-M5-10",difficulty:"easy",skill:"Reconhecer vocabulário de animais de estimação em inglês.",statement:"Veja a imagem. Qual é o pet?",instruction:"Veja a imagem, ouça as opções e arraste o áudio correto.",alts:["TURTLE","HAMSTER","FISH"],answer:"A",media:"Imagem: tartaruga; imagem/contexto → áudio."},{image:A.turtle,alt:"Tartaruga",semantic:"turtle"}),
ts({id:"EN1-M5-11",difficulty:"medium",skill:"Compreender oralmente uma frase curta sobre animal de estimação.",statement:"Ouça e escolha a imagem correta.",instruction:"Ouça a frase e toque na cena correta.",alts:["personagem com cachorro","personagem com gato","personagem com coelho"],answer:"B",media:"Áudio obrigatório: I have a cat.; áudio → imagem.",audio:"I have a cat."},[visual("A",A.dog,"Menino com cachorro","person-dog",false),visual("B",A.cat,"Menino com gato","person-cat",true),visual("C",A.rabbit,"Menino com coelho","person-rabbit",false)]),
dd({id:"EN1-M5-12",difficulty:"hard",skill:"Integrar tamanho, cor e animal em uma expressão oral curta.",statement:"Veja a imagem e ouça. Qual opção combina?",instruction:"Veja o gato, ouça as opções e arraste o áudio correto.",alts:["SMALL WHITE CAT","BIG WHITE CAT","SMALL BLACK CAT"],answer:"A",media:"Imagem obrigatória: gato pequeno branco; imagem/contexto → áudio.",assetStatus:"CANONICAL_SMALL_CAT_VISUAL_GATE"},{image:A.smallCat,alt:"Gato pequeno; cor sob verificação visual no gate",semantic:"small white cat"})
];
const M={id:"duduq-english-y1-module-05",version:"2.3.0-homolog-r147",subject:"english",year:1,module:5,title:"Pets, Colors & Size",description:"Conteúdo Oficial v2.3 / Y1_EARLY_LITERACY R0.",estimatedMinutes:6,pedagogyPolicy:{specification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",contentSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",profile:PROFILE,readingDefault:"R0",autonomousEnglishReadingRequired:false,audioRepeatable:true,imagesLargeUnambiguous:true},visualCompositionPolicy:{helper:"M05VisualComposition",localOnly:true,failClosed:true,q11:{questionId:"EN1-M5-11",classification:"LOCAL_COMPOSITION_PROVEN"},q12:{classification:"CANONICAL_SMALL_CAT_VISUAL_GATE",source:A.smallCat}},factory:{tag:"official-y1-m05-v2.3-r147",engine:"Canary R147",core:"1.0.12",targetShooter:"1.0.21",dragDrop:"2.0.24",assetCatalog:`Assets-DuduQ @ ${PIN}`},activities:Q.map((q,i)=>({id:`Y1-M05-A${String(i+1).padStart(2,"0")}`,title:"PETS, COLORS & SIZE",mechanic:q.delivery.mechanic,skill:{description:q.skill.description},questions:[q]}))};
window.DUDUQ_CONTENT.english.year1.module05=Object.freeze(M);
})();