/* DUDUQ Y1 M05 — Conteúdo Oficial v2.3 — Canary R147 */
(function(){
"use strict";
window.DUDUQ_CONTENT=window.DUDUQ_CONTENT||{};window.DUDUQ_CONTENT.english=window.DUDUQ_CONTENT.english||{};window.DUDUQ_CONTENT.english.year1=window.DUDUQ_CONTENT.english.year1||{};
const PROFILE="Y1_EARLY_LITERACY",PIN="f0f8bed8e8c24fad4eae204bf4a5cc84a8d8263f",ROOT=`https://raw.githubusercontent.com/augustoborgessousa93/Assets-DuduQ/${PIN}/Imagens%20Ilustrativa/`;
const U=f=>ROOT+f.split("/").map(encodeURIComponent).join("/");
const A=Object.freeze({cat:U("Gato.png"),dog:U("Cachorro.png"),fish:U("peixe.png"),rabbit:U("coelho.png"),hamster:U("hamster.png"),bird:U("ave.png"),turtle:U("tartaruga.png"),smallCat:U("small cat -gato pequeno.png"),person:U("boy_menino_child_boy_s4xru5.png")});
function base(s){return{id:s.id,subject:"english",year:1,module:5,skill:{code:null,description:s.skill},difficulty:s.difficulty,statement:s.statement,instruction:s.instruction,contentLanguage:"en",instructionLanguage:"pt-BR",feedbackLanguage:"pt-BR",...(s.audio?{audio:{enabled:true,text:s.audio,spokenText:s.audio,language:"en-US",speechLocale:"en-US",role:"stimulus",repeatable:true,fallback:"speech-synthesis"}}:{}),alternatives:s.alts.map((text,i)=>({id:"ABC"[i],text})),answer:{type:"single",value:s.answer},feedback:{correct:"Muito bem!",incorrect:"Ouça novamente, observe a pista e tente outra vez.",language:"pt-BR"},metadata:{screenTitle:s.topic,activityTitle:s.topic,sourceStatus:s.status,sourceSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",pedagogySpecification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",sourceStatement:s.statement,sourceAlternatives:s.alts.slice(),sourceAnswer:s.answer,sourceMedia:s.media,literacyDemand:"R0",readingEssential:false,yearProfile:PROFILE,instructionAudioFallback:{enabled:true,language:"pt-BR",text:s.instruction,mode:"speech-synthesis-or-recorded"},canonicalAssetsRequired:true,noProceduralAsset:true,...(s.assetStatus?{assetStatus:s.assetStatus}:{})}}}
function dd(s,v){const q=base(s),tid=`${s.id}-answer-target`;q.delivery={mechanic:"drag-drop",preferred:["drag-drop"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.payload={mode:"single-choice",strategy:"association",options:{shuffleItems:false,shuffleTargets:false,maxAttempts:3},retry:{maxAttempts:3,wrongBehaviour:"reset-item"},items:s.alts.map((text,i)=>{const id="ABC"[i],ok=id===s.answer;return{id,label:String(i+1),spokenText:text,speechLocale:"en-US",audioDescription:`Ouvir: ${text}`,alt:`Opção de áudio ${id}`,required:ok,...(ok?{targetId:tid}:{})}}),targets:[{id:tid,label:"",image:{src:v.image,alt:v.alt},imageUrl:v.image,alt:v.alt,accessibleLabel:v.alt,capacity:1,maxItems:1,kind:"box",...(v.localComposition?{localComposition:v.localComposition}:{})}]};q.metadata.dragDropChoice={singleEditorialAnswer:s.answer,visibleLabels:"numeric-only",optionAudioRequired:true,correctTargetId:tid,contextSemantic:v.semantic,localComposition:v.localComposition||null,noProceduralAsset:true};return q}
function scene(id,image,alt,required){return{id,label:"",image,alt,accessibleLabel:alt,required,localComposition:{helper:"M05VisualComposition",type:"canonical-person-plus-pet",person:A.person,pet:image,failClosed:true}}}
function ts(s,items){const q=base(s);q.delivery={mechanic:"target-shooter",preferred:["target-shooter"],blocked:["smart-sentence"],allowImage:true,allowAudio:true};q.metadata.targetShooter={audioText:s.audio,mode:"audio-to-image",shape:"balloon",correctIds:[s.answer],difficulty:{speed:.26,objectCount:3,spawnIntervalMs:950,requiredCorrect:1,targetSize:190,timeLimitMs:0,timerMode:"none"},items};return q}
const Q=[
dd({id:"EN1-M5-01",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"Observe o animal e ouça as opções em inglês e toque no áudio que nomeia corretamente o que você vê.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["cat","dog","fish"],answer:"B",topic:"ANIMALS",media:"Imagem obrigatória: dog. Formato: imagem/contexto → áudio."},{image:A.dog,alt:"Cachorro",semantic:"dog"}),
dd({id:"EN1-M5-02",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"Ouça as opções em inglês e toque no áudio que nomeia corretamente o animal da imagem.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["dog","fish","cat"],answer:"C",topic:"ANIMALS",media:"Imagem obrigatória: cat. Formato: imagem/contexto → áudio."},{image:A.cat,alt:"Gato",semantic:"cat"}),
dd({id:"EN1-M5-03",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"Ouça as opções e toque no áudio que corresponde do animal.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["fish","dog","cat"],answer:"A",topic:"ANIMALS",media:"Imagem obrigatória: fish. Formato: imagem/contexto → áudio."},{image:A.fish,alt:"Peixe",semantic:"fish"}),
dd({id:"EN1-M5-04",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"A imagem mostra um animal. Ouça as opções e toque no áudio correspondente. em inglês. Ouça as opções antes de responder.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["dog","rabbit","cat"],answer:"B",topic:"ANIMALS",media:"Imagem obrigatória: rabbit. Formato: imagem/contexto → áudio."},{image:A.rabbit,alt:"Coelho",semantic:"rabbit"}),
dd({id:"EN1-M5-05",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"Encontre o cartão que nomeia o animal mostrado. Ouça as opções antes de responder.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["dog","cat","hamster"],answer:"C",topic:"ANIMALS",media:"Imagem obrigatória: hamster. Formato: imagem/contexto → áudio."},{image:A.hamster,alt:"Hamster",semantic:"hamster"}),
dd({id:"EN1-M5-06",status:"Ajustar",difficulty:"easy",skill:"Identificar animais/bichos de estimação em inglês.",statement:"Qual opção identifica corretamente o animal em inglês? Ouça as opções antes de responder.",instruction:"Observe o animal, ouça as opções e arraste o áudio correto.",alts:["bird","dog","cat"],answer:"A",topic:"ANIMALS",media:"Imagem obrigatória: bird. Formato: imagem/contexto → áudio."},{image:A.bird,alt:"Pássaro",semantic:"bird"}),
dd({id:"EN1-M5-07",status:"Ajustar",difficulty:"easy",skill:"Compreender big em contraste visual com small.",statement:"Observe os dois cachorros. Toque no cachorro big. Ouça as opções antes de responder.",instruction:"Observe os dois cachorros, ouça as opções e arraste o áudio correto.",alts:["small dog","big dog","brown cat"],answer:"B",topic:"COLORS",media:"Imagem obrigatória: dois cachorros iguais em tamanhos claramente diferentes; áudio EN recomendado: big. Formato: imagem/contexto → áudio."},{image:A.dog,alt:"Dois cachorros iguais em tamanhos claramente diferentes",semantic:"same dog big versus small",localComposition:{helper:"M05VisualComposition",type:"same-canonical-animal-size-pair",source:A.dog,failClosed:true}}),
dd({id:"EN1-M5-08",status:"Ajustar",difficulty:"easy",skill:"Compreender small em contraste visual com big.",statement:"Observe os dois gatos. Toque no gato small. Ouça as opções antes de responder.",instruction:"Observe os dois gatos, ouça as opções e arraste o áudio correto.",alts:["big cat","brown dog","small cat"],answer:"C",topic:"COLORS",media:"Imagem obrigatória: dois gatos iguais em tamanhos claramente diferentes; áudio EN recomendado: small. Formato: imagem/contexto → áudio."},{image:A.cat,alt:"Dois gatos iguais em tamanhos claramente diferentes",semantic:"same cat big versus small",localComposition:{helper:"M05VisualComposition",type:"same-canonical-animal-size-pair",source:A.cat,failClosed:true}}),
dd({id:"EN1-M5-09",status:"Ajustar",difficulty:"medium",skill:"Combinar cor + pet em uma expressão curta.",statement:"Observe o cachorro marrom. Qual expressão descreve a imagem? Ouça as opções antes de responder.",instruction:"Observe o cachorro, ouça as opções e arraste o áudio correto.",alts:["brown dog","white dog","brown cat"],answer:"A",topic:"COLORS",media:"Imagem obrigatória: brown dog. Formato: imagem/contexto → áudio.",assetStatus:"CANONICAL_DIRECT_VISUAL_GATE"},{image:A.dog,alt:"Cachorro marrom",semantic:"brown dog"}),
dd({id:"EN1-M5-10",status:"Reescrever",difficulty:"medium",skill:"Completar um chunk modelado com um pet ainda não usado como resposta no módulo.",statement:"Observe a tartaruga. Complete a fala: “It’s a ___.” Ouça as opções antes de responder.",instruction:"Observe a tartaruga, ouça as opções e arraste o áudio correto.",alts:["dog","turtle","fish"],answer:"B",topic:"ANIMALS",media:"Imagem obrigatória: turtle. Formato: imagem/contexto → áudio."},{image:A.turtle,alt:"Tartaruga",semantic:"turtle"}),
ts({id:"EN1-M5-11",status:"Reescrever",difficulty:"medium",skill:"Compreender o chunk “I have a...” com apoio de imagem.",statement:"Observe o personagem com um gato. Ouça: “I have a cat.” Qual imagem combina com a fala?",instruction:"Ouça a frase e toque na cena correta.",alts:["personagem com um cachorro","personagem com um coelho","personagem com um gato"],answer:"C",topic:"ANIMALS",media:"Áudio EN obrigatório: I have a cat. + três imagens de personagens fictícios com pets diferentes. Formato: áudio → imagem.",audio:"I have a cat."},[scene("A",A.dog,"Menino com cachorro",false),scene("B",A.rabbit,"Menino com coelho",false),scene("C",A.cat,"Menino com gato",true)]),
dd({id:"EN1-M5-12",status:"Ajustar",difficulty:"hard",skill:"Compreender uma descrição curta com tamanho + cor + animal.",statement:"Observe o gato branco e pequeno. Qual descrição combina com a imagem? Ouça as opções antes de responder.",instruction:"Observe o gato, ouça as opções e arraste o áudio correto.",alts:["It’s a small white cat.","It’s a big white cat.","It’s a small brown cat."],answer:"A",topic:"COLORS",media:"Imagem obrigatória: small white cat. Formato: imagem/contexto → áudio.",assetStatus:"CANONICAL_SMALL_CAT_VISUAL_GATE"},{image:A.smallCat,alt:"Gato pequeno; pelagem sob verificação visual no gate",semantic:"small white cat"})
];
const M={id:"duduq-english-y1-module-05",version:"2.3.1-official-r147",subject:"english",year:1,module:5,title:"Pets, Colors & Size",description:"Conteúdo Oficial v2.3 / Y1_EARLY_LITERACY R0.",estimatedMinutes:6,pedagogyPolicy:{specification:"DUDUQ_FACTORY_PEDAGOGICAL_SPECIFICATION_v1.2",contentSpecification:"DUDUQ_Ingles_1ao5_Revisao_Alfabetizacao_Multimodal_v2.3",profile:PROFILE,readingDefault:"R0",readingMax:"R1_NONESSENTIAL_ONLY",autonomousEnglishReadingRequired:false,audioRepeatable:true,imagesLargeUnambiguous:true},visualCompositionPolicy:{helper:"M05VisualComposition",localOnly:true,failClosed:true,q07:{questionId:"EN1-M5-07",classification:"LOCAL_COMPOSITION_PROVEN",source:A.dog},q08:{questionId:"EN1-M5-08",classification:"LOCAL_COMPOSITION_PROVEN",source:A.cat},q11:{questionId:"EN1-M5-11",classification:"LOCAL_COMPOSITION_PROVEN"},q12:{questionId:"EN1-M5-12",classification:"CANONICAL_SMALL_CAT_VISUAL_GATE",source:A.smallCat}},factory:{tag:"official-y1-m05-v2.3-r147",engine:"Canary R147",core:"1.0.12",targetShooter:"1.0.21",dragDrop:"2.0.24",assetCatalog:`Assets-DuduQ @ ${PIN}`},activities:Q.map((q,i)=>({id:`Y1-M05-A${String(i+1).padStart(2,"0")}`,title:q.metadata.activityTitle,mechanic:q.delivery.mechanic,skill:{description:q.skill.description},questions:[q]}))};
window.DUDUQ_CONTENT.english.year1.module05=Object.freeze(M);
})();