/* DUDUQ English Year 3 — Module 03 — source-approved thin content */
(function(){"use strict";const F=window.DuduQYear3Factory;if(!F)throw new Error("DuduQYear3Factory não carregado.");F.publish({module:3,version:"1.0.0-scale-bootstrap",title:"Family, Toys & Animals",objective:"Compreender e produzir descrições curtas sobre personagens, familiares fictícios, brinquedos e animais, usando he/she, idade, preferência e plural em contexto.",items:[
{id:"EN3-M3-01",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer membro da família em inglês com apoio visual.",prompt:"Observe a pessoa indicada e escolha o termo de família em inglês.",alternatives:[{id:"A",text:"mother"},{id:"B",text:"sister"},{id:"C",text:"father"},{id:"D",text:"brother"}],answer:{id:"B",text:"sister"},media:"Imagem obrigatória: sister. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"sister",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-02",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer membro da família em inglês com apoio visual.",prompt:"Qual palavra em inglês identifica o familiar mostrado?",alternatives:[{id:"A",text:"mother"},{id:"B",text:"father"},{id:"C",text:"brother"},{id:"D",text:"sister"}],answer:{id:"C",text:"brother"},media:"Imagem obrigatória: brother. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"brother",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-03",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer membro da família em inglês com apoio visual.",prompt:"Toque no cartão que corresponde ao membro da família.",alternatives:[{id:"A",text:"father"},{id:"B",text:"sister"},{id:"C",text:"brother"},{id:"D",text:"mother"}],answer:{id:"D",text:"mother"},media:"Imagem obrigatória: mother. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"mother",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-04",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer membro da família em inglês com apoio visual.",prompt:"A imagem destaca um familiar. Escolha o nome em inglês.",alternatives:[{id:"A",text:"grandfather"},{id:"B",text:"mother"},{id:"C",text:"father"},{id:"D",text:"sister"}],answer:{id:"A",text:"grandfather"},media:"Imagem obrigatória: grandfather. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"grandfather",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-05",status:"Manter",difficulty:"Média",skill:"Compreensão multimodal",ability:"Relacionar he/she à apresentação da família.",prompt:"Complete: “___ is my sister.”",alternatives:[{id:"A",text:"He"},{id:"B",text:"She"},{id:"C",text:"They"},{id:"D",text:"It"}],answer:{id:"B",text:"She"},media:"Imagem: sister. Formato sugerido: Sentence builder / escolha.",format:"Sentence builder / escolha.",visualQuery:"sister",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-06",status:"Manter",difficulty:"Média",skill:"Compreensão multimodal",ability:"Relacionar he/she à apresentação da família.",prompt:"Complete: “___ is my brother.”",alternatives:[{id:"A",text:"She"},{id:"B",text:"They"},{id:"C",text:"He"},{id:"D",text:"It"}],answer:{id:"C",text:"He"},media:"Imagem: brother. Formato sugerido: Sentence builder / escolha.",format:"Sentence builder / escolha.",visualQuery:"brother",listenText:"",mechanic:"drag-drop",topic:"FAMILY"},
{id:"EN3-M3-07",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Relacionar personagem e idade em uma frase curta.",prompt:"Observe a irmã de Leo com a etiqueta “Age: 8”. Qual frase descreve a personagem?",alternatives:[{id:"A",text:"She is six years old."},{id:"B",text:"She is seven years old."},{id:"C",text:"She is nine years old."},{id:"D",text:"She is eight years old."}],answer:{id:"D",text:"She is eight years old."},media:"Cartão de personagem fictícia; não usar dados reais. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"8",listenText:"",mechanic:"bubble-pop",topic:"FAMILY & AGE"},
{id:"EN3-M3-08",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer vocabulário de brinquedos com apoio visual.",prompt:"Observe o brinquedo mostrado. Qual palavra está correta?",alternatives:[{id:"A",text:"ball"},{id:"B",text:"kite"},{id:"C",text:"doll"},{id:"D",text:"train"}],answer:{id:"A",text:"ball"},media:"Imagem obrigatória: ball. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"ball",listenText:"",mechanic:"drag-drop",topic:"TOYS"},
{id:"EN3-M3-09",status:"Ajustar",difficulty:"Média",skill:"Leitura + produção guiada",ability:"Completar frase de preferência com vocabulário de brinquedos.",prompt:"Observe a pipa no cartão de preferência. Complete: “My favorite toy is a ___.”",alternatives:[{id:"A",text:"kite"},{id:"B",text:"ball"},{id:"C",text:"doll"},{id:"D",text:"train"}],answer:{id:"A",text:"kite"},media:"Imagem obrigatória: kite em cartão fictício. Formato sugerido: Sentence builder / escolha.",format:"Sentence builder / escolha.",visualQuery:"kite",listenText:"",mechanic:"drag-drop",topic:"TOYS"},
{id:"EN3-M3-10",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Reconhecer vocabulário de animais com apoio visual.",prompt:"Observe o animal mostrado. Qual palavra está correta?",alternatives:[{id:"A",text:"rabbit"},{id:"B",text:"duck"},{id:"C",text:"turtle"},{id:"D",text:"cat"}],answer:{id:"C",text:"turtle"},media:"Imagem obrigatória: turtle. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"turtle",listenText:"",mechanic:"drag-drop",topic:"ANIMALS"},
{id:"EN3-M3-11",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Reconhecer singular/plural em vocabulário conhecido com apoio visual.",prompt:"Observe várias tartarugas. Qual palavra descreve corretamente a imagem?",alternatives:[{id:"A",text:"turtle"},{id:"B",text:"turtles"},{id:"C",text:"duck"},{id:"D",text:"ducks"}],answer:{id:"B",text:"turtles"},media:"Imagem obrigatória: pelo menos três turtles. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"three turtles",listenText:"",mechanic:"drag-drop",topic:"ANIMALS"},
{id:"EN3-M3-12",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade + cor + animal.",prompt:"Observe 3 patos amarelos. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"three yellow ducks"},{id:"B",text:"three brown ducks"},{id:"C",text:"two yellow ducks"},{id:"D",text:"three yellow turtles"}],answer:{id:"A",text:"three yellow ducks"},media:"Imagem obrigatória: 3 yellow ducks. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"3 yellow ducks",listenText:"",mechanic:"drag-drop",topic:"ANIMALS & NUMBERS"},
{id:"EN3-M3-13",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Integrar quantidade + cor + animal.",prompt:"Observe 7 gatos brancos. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"seven white cats"},{id:"B",text:"seven black cats"},{id:"C",text:"six white cats"},{id:"D",text:"seven white dogs"}],answer:{id:"A",text:"seven white cats"},media:"Imagem obrigatória: 7 white cats. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"7 white cats",listenText:"",mechanic:"drag-drop",topic:"ANIMALS & NUMBERS"},
{id:"EN3-M3-14",status:"Reescrever",difficulty:"Difícil",skill:"Leitura",ability:"Compreender uma descrição de idade em contexto familiar fictício.",prompt:"O cartão mostra “Grandfather – Age: 50”. Qual frase descreve a pessoa?",alternatives:[{id:"A",text:"He is forty years old."},{id:"B",text:"He is fifty years old."},{id:"C",text:"She is fifty years old."},{id:"D",text:"He has fifty years."}],answer:{id:"B",text:"He is fifty years old."},media:"Cartão de personagem fictício; sem dados reais. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"grandfather",listenText:"",mechanic:"bubble-pop",topic:"FAMILY & AGE"},
{id:"EN3-M3-15",status:"Reescrever",difficulty:"Difícil",skill:"Compreensão multimodal",ability:"Integrar quantidade, cor e plural em uma descrição curta.",prompt:"Observe 2 coelhos marrons. Qual expressão descreve a imagem?",alternatives:[{id:"A",text:"two brown rabbits"},{id:"B",text:"three brown rabbits"},{id:"C",text:"two white rabbits"},{id:"D",text:"two brown ducks"}],answer:{id:"A",text:"two brown rabbits"},media:"Imagem obrigatória: 2 brown rabbits. Formato sugerido: Imagem → expressão.",format:"Imagem → expressão.",visualQuery:"2 brown rabbits",listenText:"",mechanic:"drag-drop",topic:"ANIMALS & NUMBERS"}
]});})();
