/* DUDUQ English Year 3 — Module 02 — source-approved thin content */
(function(){"use strict";const F=window.DuduQYear3Factory;if(!F)throw new Error("DuduQYear3Factory não carregado.");F.publish({module:2,version:"1.0.0-scale-bootstrap",title:"Numbers 1–50 & Age",objective:"Compreender números até 50 e participar de uma troca simples sobre idade, com leitura e escuta de numerais/palavras.",items:[
{id:"EN3-M2-01",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Observe o numeral e escolha sua forma escrita em inglês.",alternatives:[{id:"A",text:"twenty"},{id:"B",text:"twenty-one"},{id:"C",text:"twenty-five"},{id:"D",text:"thirty"}],answer:{id:"B",text:"twenty-one"},media:"Imagem recomendada: numeral 21. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"21",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-02",status:"Reescrever",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Observe o numeral 24. Qual é sua forma escrita em inglês?",alternatives:[{id:"A",text:"twenty-two"},{id:"B",text:"twenty-four"},{id:"C",text:"twenty-five"},{id:"D",text:"thirty-four"}],answer:{id:"B",text:"twenty-four"},media:"Cartão com numeral 24; áudio das alternativas sob toque. Formato sugerido: Numeral → palavra.",format:"Numeral → palavra.",visualQuery:"24",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-03",status:"Ajustar",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Qual opção escreve corretamente o número em inglês?",alternatives:[{id:"A",text:"twenty"},{id:"B",text:"twenty-one"},{id:"C",text:"twenty-five"},{id:"D",text:"thirty"}],answer:{id:"D",text:"thirty"},media:"Imagem recomendada: numeral 30. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"30",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-04",status:"Reescrever",difficulty:"Fácil",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Observe o numeral 33. Qual é sua forma escrita em inglês?",alternatives:[{id:"A",text:"thirty-three"},{id:"B",text:"thirty"},{id:"C",text:"twenty-three"},{id:"D",text:"forty-three"}],answer:{id:"A",text:"thirty-three"},media:"Cartão com numeral 33. Formato sugerido: Numeral → palavra.",format:"Numeral → palavra.",visualQuery:"33",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-05",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Toque na forma escrita em inglês que corresponde ao numeral.",alternatives:[{id:"A",text:"twenty"},{id:"B",text:"forty"},{id:"C",text:"twenty-one"},{id:"D",text:"twenty-five"}],answer:{id:"B",text:"forty"},media:"Imagem recomendada: numeral 40. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"40",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-06",status:"Reescrever",difficulty:"Média",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"Observe o numeral 47. Qual é sua forma escrita em inglês?",alternatives:[{id:"A",text:"forty-five"},{id:"B",text:"forty-seven"},{id:"C",text:"thirty-seven"},{id:"D",text:"seventy-four"}],answer:{id:"B",text:"forty-seven"},media:"Cartão com numeral 47. Formato sugerido: Numeral → palavra.",format:"Numeral → palavra.",visualQuery:"47",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-07",status:"Ajustar",difficulty:"Média",skill:"Compreensão multimodal",ability:"Ler, ouvir e compreender números de 1 a 50.",prompt:"O cartão mostra um número. Escolha a escrita correta em inglês.",alternatives:[{id:"A",text:"twenty"},{id:"B",text:"twenty-one"},{id:"C",text:"twenty-five"},{id:"D",text:"fifty"}],answer:{id:"D",text:"fifty"},media:"Imagem recomendada: numeral 50. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"50",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-08",status:"Ajustar",difficulty:"Fácil",skill:"Leitura / compreensão pragmática",ability:"Selecionar a pergunta adequada para saber a idade.",prompt:"Leo quer saber a idade de Maya. Qual pergunta ele deve fazer?",alternatives:[{id:"A",text:"How old are you?"},{id:"B",text:"What is your favorite toy?"},{id:"C",text:"Where is the ruler?"},{id:"D",text:"How do you spell dog?"}],answer:{id:"A",text:"How old are you?"},media:"Mini cena com personagens fictícios; áudio EN recomendado. Formato sugerido: Escolha contextual.",format:"Escolha contextual.",visualQuery:"age",listenText:"",mechanic:"bubble-pop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-09",status:"Ajustar",difficulty:"Média",skill:"Leitura + produção guiada",ability:"Completar a estrutura “I am ... years old”.",prompt:"Complete a resposta: “I am 9 ___ old.”",alternatives:[{id:"A",text:"day"},{id:"B",text:"years"},{id:"C",text:"name"},{id:"D",text:"number"}],answer:{id:"B",text:"years"},media:"Sem mídia obrigatória; pode ser sentence builder. Formato sugerido: Sentence builder / escolha.",format:"Sentence builder / escolha.",visualQuery:"9",listenText:"",mechanic:"bubble-pop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-10",status:"Reescrever",difficulty:"Média",skill:"Leitura / compreensão pragmática",ability:"Selecionar uma resposta de idade adequada ao contexto.",prompt:"Maya tem 10 anos. Qual resposta combina com “How old are you?”",alternatives:[{id:"A",text:"I am ten years old."},{id:"B",text:"I have ten pencils."},{id:"C",text:"My name is Ten."},{id:"D",text:"It is ten o’clock."}],answer:{id:"A",text:"I am ten years old."},media:"Personagem fictícia Maya com número 10 como apoio visual. Formato sugerido: Escolha contextual.",format:"Escolha contextual.",visualQuery:"10",listenText:"How old are you?",mechanic:"bubble-pop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-11",status:"Reescrever",difficulty:"Média",skill:"Escuta",ability:"Relacionar a forma oral do número em inglês ao numeral.",prompt:"Ouça “thirty-two”. Qual numeral corresponde ao que você ouviu?",alternatives:[{id:"A",text:"23"},{id:"B",text:"30"},{id:"C",text:"32"},{id:"D",text:"42"}],answer:{id:"C",text:"32"},media:"Áudio EN obrigatório: “thirty-two”. Formato sugerido: Escuta → numeral.",format:"Escuta → numeral.",visualQuery:"32",listenText:"thirty-two",mechanic:"target-shooter",topic:"NUMBERS & AGE"},
{id:"EN3-M2-12",status:"Reescrever",difficulty:"Média",skill:"Escuta",ability:"Relacionar a forma oral do número em inglês ao numeral.",prompt:"Ouça “forty-eight”. Qual numeral corresponde ao que você ouviu?",alternatives:[{id:"A",text:"18"},{id:"B",text:"38"},{id:"C",text:"48"},{id:"D",text:"50"}],answer:{id:"C",text:"48"},media:"Áudio EN obrigatório: “forty-eight”. Formato sugerido: Escuta → numeral.",format:"Escuta → numeral.",visualQuery:"48",listenText:"forty-eight",mechanic:"target-shooter",topic:"NUMBERS & AGE"},
{id:"EN3-M2-13",status:"Reescrever",difficulty:"Média",skill:"Leitura",ability:"Relacionar numeral e forma escrita em inglês sem exigir contagem extensa.",prompt:"Observe o numeral 25. Qual é sua forma escrita em inglês?",alternatives:[{id:"A",text:"twenty"},{id:"B",text:"twenty-five"},{id:"C",text:"thirty-five"},{id:"D",text:"fifty-two"}],answer:{id:"B",text:"twenty-five"},media:"Imagem obrigatória: numeral 25 grande e nítido. Formato sugerido: Imagem → palavra/frase.",format:"Imagem → palavra/frase.",visualQuery:"25",listenText:"",mechanic:"drag-drop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-14",status:"Ajustar",difficulty:"Difícil",skill:"Leitura",ability:"Usar informação de uma ficha para selecionar uma resposta de idade.",prompt:"No cartão de Ana está escrito “Age: 12”. Qual resposta combina com “How old are you?”",alternatives:[{id:"A",text:"I am ten years old."},{id:"B",text:"I am eleven years old."},{id:"C",text:"I am twelve years old."},{id:"D",text:"I am twenty years old."}],answer:{id:"C",text:"I am twelve years old."},media:"Cartão de personagem fictícia Ana. Formato sugerido: Leitura funcional + escolha.",format:"Leitura funcional + escolha.",visualQuery:"12",listenText:"How old are you?",mechanic:"bubble-pop",topic:"NUMBERS & AGE"},
{id:"EN3-M2-15",status:"Reescrever",difficulty:"Difícil",skill:"Escuta",ability:"Compreender auditivamente números até 50.",prompt:"Ouça “forty-nine” e escolha o numeral correto.",alternatives:[{id:"A",text:"39"},{id:"B",text:"45"},{id:"C",text:"49"},{id:"D",text:"50"}],answer:{id:"C",text:"49"},media:"Áudio EN obrigatório: “forty-nine”. Formato sugerido: Escuta → numeral.",format:"Escuta → numeral.",visualQuery:"49",listenText:"forty-nine",mechanic:"target-shooter",topic:"NUMBERS & AGE"}
]});})();
